//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.31 at 03:26:52 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             This transaction returns transaction history information for the account and other criteria specified
 *             </summary>
 * 
 * <p>Java class for AccountTransactionHistoryRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AccountTransactionHistoryRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opensolutions.com/CoreApi}RequestBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="DebitCreditOnly" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExternalRtxnDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FromAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="FromCheckNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="InternalRtxnDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsCustomerView" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsErrorCorrect" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsIncludeBalanceDetail" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsRejected" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsResultingBalance" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsReversed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="MaximumRows" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="PreviousRunningBalance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="RtxnReportGroupCodes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RtxnTypeCodes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SearchDateOption" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="SortBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SortOrder" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ThroughAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="ThroughCheckNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ThroughDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="TimeUniqueExtension" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="TransactionReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AccountTransactionHistoryRequest", propOrder = {
    "accountNumber",
    "debitCreditOnly",
    "externalRtxnDescription",
    "fromAmount",
    "fromCheckNumber",
    "fromDate",
    "internalRtxnDescription",
    "isCustomerView",
    "isErrorCorrect",
    "isIncludeBalanceDetail",
    "isRejected",
    "isResultingBalance",
    "isReversed",
    "maximumRows",
    "previousRunningBalance",
    "rtxnReportGroupCodes",
    "rtxnTypeCodes",
    "searchDateOption",
    "sortBy",
    "sortOrder",
    "throughAmount",
    "throughCheckNumber",
    "throughDate",
    "timeUniqueExtension",
    "transactionReferenceNumber"
})
public class AccountTransactionHistoryRequest
    extends RequestBase
{

    @XmlElement(name = "AccountNumber", nillable = true)
    protected Long accountNumber;
    @XmlElement(name = "DebitCreditOnly", nillable = true)
    protected String debitCreditOnly;
    @XmlElement(name = "ExternalRtxnDescription", nillable = true)
    protected String externalRtxnDescription;
    @XmlElement(name = "FromAmount", nillable = true)
    protected Double fromAmount;
    @XmlElement(name = "FromCheckNumber", nillable = true)
    protected Long fromCheckNumber;
    @XmlElement(name = "FromDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fromDate;
    @XmlElement(name = "InternalRtxnDescription", nillable = true)
    protected String internalRtxnDescription;
    @XmlElement(name = "IsCustomerView", nillable = true)
    protected Boolean isCustomerView;
    @XmlElement(name = "IsErrorCorrect", nillable = true)
    protected Boolean isErrorCorrect;
    @XmlElement(name = "IsIncludeBalanceDetail", nillable = true)
    protected Boolean isIncludeBalanceDetail;
    @XmlElement(name = "IsRejected", nillable = true)
    protected Boolean isRejected;
    @XmlElement(name = "IsResultingBalance", nillable = true)
    protected Boolean isResultingBalance;
    @XmlElement(name = "IsReversed", nillable = true)
    protected Boolean isReversed;
    @XmlElement(name = "MaximumRows", nillable = true)
    protected Long maximumRows;
    @XmlElement(name = "PreviousRunningBalance", nillable = true)
    protected Double previousRunningBalance;
    @XmlElement(name = "RtxnReportGroupCodes", nillable = true)
    protected String rtxnReportGroupCodes;
    @XmlElement(name = "RtxnTypeCodes", nillable = true)
    protected String rtxnTypeCodes;
    @XmlElement(name = "SearchDateOption", nillable = true)
    protected Integer searchDateOption;
    @XmlElement(name = "SortBy", nillable = true)
    protected String sortBy;
    @XmlElement(name = "SortOrder", nillable = true)
    protected String sortOrder;
    @XmlElement(name = "ThroughAmount", nillable = true)
    protected Double throughAmount;
    @XmlElement(name = "ThroughCheckNumber", nillable = true)
    protected Long throughCheckNumber;
    @XmlElement(name = "ThroughDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar throughDate;
    @XmlElement(name = "TimeUniqueExtension", nillable = true)
    protected Long timeUniqueExtension;
    @XmlElement(name = "TransactionReferenceNumber", nillable = true)
    protected String transactionReferenceNumber;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountNumber(Long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the debitCreditOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitCreditOnly() {
        return debitCreditOnly;
    }

    /**
     * Sets the value of the debitCreditOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitCreditOnly(String value) {
        this.debitCreditOnly = value;
    }

    /**
     * Gets the value of the externalRtxnDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalRtxnDescription() {
        return externalRtxnDescription;
    }

    /**
     * Sets the value of the externalRtxnDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalRtxnDescription(String value) {
        this.externalRtxnDescription = value;
    }

    /**
     * Gets the value of the fromAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFromAmount() {
        return fromAmount;
    }

    /**
     * Sets the value of the fromAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFromAmount(Double value) {
        this.fromAmount = value;
    }

    /**
     * Gets the value of the fromCheckNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFromCheckNumber() {
        return fromCheckNumber;
    }

    /**
     * Sets the value of the fromCheckNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFromCheckNumber(Long value) {
        this.fromCheckNumber = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the internalRtxnDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalRtxnDescription() {
        return internalRtxnDescription;
    }

    /**
     * Sets the value of the internalRtxnDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalRtxnDescription(String value) {
        this.internalRtxnDescription = value;
    }

    /**
     * Gets the value of the isCustomerView property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCustomerView() {
        return isCustomerView;
    }

    /**
     * Sets the value of the isCustomerView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCustomerView(Boolean value) {
        this.isCustomerView = value;
    }

    /**
     * Gets the value of the isErrorCorrect property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsErrorCorrect() {
        return isErrorCorrect;
    }

    /**
     * Sets the value of the isErrorCorrect property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsErrorCorrect(Boolean value) {
        this.isErrorCorrect = value;
    }

    /**
     * Gets the value of the isIncludeBalanceDetail property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsIncludeBalanceDetail() {
        return isIncludeBalanceDetail;
    }

    /**
     * Sets the value of the isIncludeBalanceDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsIncludeBalanceDetail(Boolean value) {
        this.isIncludeBalanceDetail = value;
    }

    /**
     * Gets the value of the isRejected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRejected() {
        return isRejected;
    }

    /**
     * Sets the value of the isRejected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRejected(Boolean value) {
        this.isRejected = value;
    }

    /**
     * Gets the value of the isResultingBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsResultingBalance() {
        return isResultingBalance;
    }

    /**
     * Sets the value of the isResultingBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsResultingBalance(Boolean value) {
        this.isResultingBalance = value;
    }

    /**
     * Gets the value of the isReversed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsReversed() {
        return isReversed;
    }

    /**
     * Sets the value of the isReversed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReversed(Boolean value) {
        this.isReversed = value;
    }

    /**
     * Gets the value of the maximumRows property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaximumRows() {
        return maximumRows;
    }

    /**
     * Sets the value of the maximumRows property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaximumRows(Long value) {
        this.maximumRows = value;
    }

    /**
     * Gets the value of the previousRunningBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPreviousRunningBalance() {
        return previousRunningBalance;
    }

    /**
     * Sets the value of the previousRunningBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPreviousRunningBalance(Double value) {
        this.previousRunningBalance = value;
    }

    /**
     * Gets the value of the rtxnReportGroupCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnReportGroupCodes() {
        return rtxnReportGroupCodes;
    }

    /**
     * Sets the value of the rtxnReportGroupCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnReportGroupCodes(String value) {
        this.rtxnReportGroupCodes = value;
    }

    /**
     * Gets the value of the rtxnTypeCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnTypeCodes() {
        return rtxnTypeCodes;
    }

    /**
     * Sets the value of the rtxnTypeCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnTypeCodes(String value) {
        this.rtxnTypeCodes = value;
    }

    /**
     * Gets the value of the searchDateOption property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSearchDateOption() {
        return searchDateOption;
    }

    /**
     * Sets the value of the searchDateOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSearchDateOption(Integer value) {
        this.searchDateOption = value;
    }

    /**
     * Gets the value of the sortBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortBy() {
        return sortBy;
    }

    /**
     * Sets the value of the sortBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortBy(String value) {
        this.sortBy = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortOrder(String value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the throughAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getThroughAmount() {
        return throughAmount;
    }

    /**
     * Sets the value of the throughAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setThroughAmount(Double value) {
        this.throughAmount = value;
    }

    /**
     * Gets the value of the throughCheckNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getThroughCheckNumber() {
        return throughCheckNumber;
    }

    /**
     * Sets the value of the throughCheckNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setThroughCheckNumber(Long value) {
        this.throughCheckNumber = value;
    }

    /**
     * Gets the value of the throughDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getThroughDate() {
        return throughDate;
    }

    /**
     * Sets the value of the throughDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setThroughDate(XMLGregorianCalendar value) {
        this.throughDate = value;
    }

    /**
     * Gets the value of the timeUniqueExtension property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeUniqueExtension() {
        return timeUniqueExtension;
    }

    /**
     * Sets the value of the timeUniqueExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeUniqueExtension(Long value) {
        this.timeUniqueExtension = value;
    }

    /**
     * Gets the value of the transactionReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionReferenceNumber() {
        return transactionReferenceNumber;
    }

    /**
     * Sets the value of the transactionReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionReferenceNumber(String value) {
        this.transactionReferenceNumber = value;
    }

}
