//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.31 at 03:26:52 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import com.dep.integration.transaction.hook.fiserv.dto.jaxb.billpayhistory.ArrayOfBillPayment;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillPayHistoryResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillPayHistoryResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opensolutions.com/CoreApi}ExtensionResponseBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="BillPaymentList" type="{http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory}ArrayOfBillPayment" minOccurs="0"/&gt;
 *         &lt;element name="MoreIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPayHistoryResponse", propOrder = {
    "accountNumber",
    "billPaymentList",
    "moreIndicator",
    "sequenceNumber"
})
public class BillPayHistoryResponse
    extends ExtensionResponseBase
{

    @XmlElement(name = "AccountNumber")
    protected Long accountNumber;
    @XmlElement(name = "BillPaymentList", nillable = true)
    protected ArrayOfBillPayment billPaymentList;
    @XmlElement(name = "MoreIndicator")
    protected Boolean moreIndicator;
    @XmlElement(name = "SequenceNumber")
    protected Integer sequenceNumber;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountNumber(Long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the billPaymentList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBillPayment }
     *     
     */
    public ArrayOfBillPayment getBillPaymentList() {
        return billPaymentList;
    }

    /**
     * Sets the value of the billPaymentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBillPayment }
     *     
     */
    public void setBillPaymentList(ArrayOfBillPayment value) {
        this.billPaymentList = value;
    }

    /**
     * Gets the value of the moreIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMoreIndicator() {
        return moreIndicator;
    }

    /**
     * Sets the value of the moreIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMoreIndicator(Boolean value) {
        this.moreIndicator = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSequenceNumber(Integer value) {
        this.sequenceNumber = value;
    }

}
