//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import com.dep.integration.transaction.hook.fiserv.dto.jaxb.arrays.ArrayOfanyType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             Wrapper tag that identifies the following data is used for Input into the Core API.
 *             </summary>
 * 
 * <p>Java class for Input complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Input"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExtensionRequests" type="{http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfanyType" minOccurs="0"/&gt;
 *         &lt;element name="Requests" type="{http://www.opensolutions.com/CoreApi}ArrayOfRequestBase" minOccurs="0"/&gt;
 *         &lt;element name="UserAuthentication" type="{http://www.opensolutions.com/CoreApi}UAInput" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Input", propOrder = {
    "extensionRequests",
    "requests",
    "userAuthentication"
})
public class Input {

    @XmlElement(name = "ExtensionRequests", nillable = true)
    protected ArrayOfanyType extensionRequests;
    @XmlElement(name = "Requests", nillable = true)
    protected ArrayOfRequestBase requests;
    @XmlElement(name = "UserAuthentication", nillable = true)
    protected UAInput userAuthentication;

    /**
     * Gets the value of the extensionRequests property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfanyType }
     *     
     */
    public ArrayOfanyType getExtensionRequests() {
        return extensionRequests;
    }

    /**
     * Sets the value of the extensionRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfanyType }
     *     
     */
    public void setExtensionRequests(ArrayOfanyType value) {
        this.extensionRequests = value;
    }

    /**
     * Gets the value of the requests property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfRequestBase }
     *     
     */
    public ArrayOfRequestBase getRequests() {
        return requests;
    }

    /**
     * Sets the value of the requests property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfRequestBase }
     *     
     */
    public void setRequests(ArrayOfRequestBase value) {
        this.requests = value;
    }

    /**
     * Gets the value of the userAuthentication property.
     * 
     * @return
     *     possible object is
     *     {@link UAInput }
     *     
     */
    public UAInput getUserAuthentication() {
        return userAuthentication;
    }

    /**
     * Sets the value of the userAuthentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link UAInput }
     *     
     */
    public void setUserAuthentication(UAInput value) {
        this.userAuthentication = value;
    }

}
