//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "RequestBase");
    private final static QName _ResponseBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ResponseBase");
    private final static QName _ArrayOfError_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ArrayOfError");
    private final static QName _Error_QNAME = new QName("http://www.opensolutions.com/CoreApi", "Error");
    private final static QName _AccountTransactionHistoryRequest_QNAME = new QName("http://www.opensolutions.com/CoreApi", "AccountTransactionHistoryRequest");
    private final static QName _AccountTransactionHistoryResponse_QNAME = new QName("http://www.opensolutions.com/CoreApi", "AccountTransactionHistoryResponse");
    private final static QName _TransactionHistoryInquiryRequest_QNAME = new QName("http://www.opensolutions.com/CoreApi", "TransactionHistoryInquiryRequest");
    private final static QName _TransactionHistoryInquiryResponse_QNAME = new QName("http://www.opensolutions.com/CoreApi", "TransactionHistoryInquiryResponse");
    private final static QName _ExtensionRequestBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ExtensionRequestBase");
    private final static QName _BillPayHistoryRequest_QNAME = new QName("http://www.opensolutions.com/CoreApi", "BillPayHistoryRequest");
    private final static QName _ExtensionResponseBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ExtensionResponseBase");
    private final static QName _ArrayOfExtensionError_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ArrayOfExtensionError");
    private final static QName _ExtensionError_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ExtensionError");
    private final static QName _BillPayHistoryResponse_QNAME = new QName("http://www.opensolutions.com/CoreApi", "BillPayHistoryResponse");
    private final static QName _TransactionInput_QNAME = new QName("http://www.opensolutions.com/CoreApi", "TransactionInput");
    private final static QName _Input_QNAME = new QName("http://www.opensolutions.com/CoreApi", "Input");
    private final static QName _ArrayOfRequestBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ArrayOfRequestBase");
    private final static QName _UAInput_QNAME = new QName("http://www.opensolutions.com/CoreApi", "UAInput");
    private final static QName _TransactionOutput_QNAME = new QName("http://www.opensolutions.com/CoreApi", "TransactionOutput");
    private final static QName _Output_QNAME = new QName("http://www.opensolutions.com/CoreApi", "Output");
    private final static QName _ArrayOfResponseBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ArrayOfResponseBase");
    private final static QName _UAOutput_QNAME = new QName("http://www.opensolutions.com/CoreApi", "UAOutput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestBase }
     * 
     */
    public RequestBase createRequestBase() {
        return new RequestBase();
    }

    /**
     * Create an instance of {@link ResponseBase }
     * 
     */
    public ResponseBase createResponseBase() {
        return new ResponseBase();
    }

    /**
     * Create an instance of {@link ArrayOfError }
     * 
     */
    public ArrayOfError createArrayOfError() {
        return new ArrayOfError();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link AccountTransactionHistoryRequest }
     * 
     */
    public AccountTransactionHistoryRequest createAccountTransactionHistoryRequest() {
        return new AccountTransactionHistoryRequest();
    }

    /**
     * Create an instance of {@link AccountTransactionHistoryResponse }
     * 
     */
    public AccountTransactionHistoryResponse createAccountTransactionHistoryResponse() {
        return new AccountTransactionHistoryResponse();
    }

    /**
     * Create an instance of {@link TransactionHistoryInquiryRequest }
     * 
     */
    public TransactionHistoryInquiryRequest createTransactionHistoryInquiryRequest() {
        return new TransactionHistoryInquiryRequest();
    }

    /**
     * Create an instance of {@link TransactionHistoryInquiryResponse }
     * 
     */
    public TransactionHistoryInquiryResponse createTransactionHistoryInquiryResponse() {
        return new TransactionHistoryInquiryResponse();
    }

    /**
     * Create an instance of {@link ExtensionRequestBase }
     * 
     */
    public ExtensionRequestBase createExtensionRequestBase() {
        return new ExtensionRequestBase();
    }

    /**
     * Create an instance of {@link BillPayHistoryRequest }
     * 
     */
    public BillPayHistoryRequest createBillPayHistoryRequest() {
        return new BillPayHistoryRequest();
    }

    /**
     * Create an instance of {@link ExtensionResponseBase }
     * 
     */
    public ExtensionResponseBase createExtensionResponseBase() {
        return new ExtensionResponseBase();
    }

    /**
     * Create an instance of {@link ArrayOfExtensionError }
     * 
     */
    public ArrayOfExtensionError createArrayOfExtensionError() {
        return new ArrayOfExtensionError();
    }

    /**
     * Create an instance of {@link ExtensionError }
     * 
     */
    public ExtensionError createExtensionError() {
        return new ExtensionError();
    }

    /**
     * Create an instance of {@link BillPayHistoryResponse }
     * 
     */
    public BillPayHistoryResponse createBillPayHistoryResponse() {
        return new BillPayHistoryResponse();
    }

    /**
     * Create an instance of {@link SubmitRequest }
     * 
     */
    public SubmitRequest createSubmitRequest() {
        return new SubmitRequest();
    }

    /**
     * Create an instance of {@link TransactionInput }
     * 
     */
    public TransactionInput createTransactionInput() {
        return new TransactionInput();
    }

    /**
     * Create an instance of {@link Input }
     * 
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link ArrayOfRequestBase }
     * 
     */
    public ArrayOfRequestBase createArrayOfRequestBase() {
        return new ArrayOfRequestBase();
    }

    /**
     * Create an instance of {@link UAInput }
     * 
     */
    public UAInput createUAInput() {
        return new UAInput();
    }

    /**
     * Create an instance of {@link SubmitRequestResponse }
     * 
     */
    public SubmitRequestResponse createSubmitRequestResponse() {
        return new SubmitRequestResponse();
    }

    /**
     * Create an instance of {@link TransactionOutput }
     * 
     */
    public TransactionOutput createTransactionOutput() {
        return new TransactionOutput();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link ArrayOfResponseBase }
     * 
     */
    public ArrayOfResponseBase createArrayOfResponseBase() {
        return new ArrayOfResponseBase();
    }

    /**
     * Create an instance of {@link UAOutput }
     * 
     */
    public UAOutput createUAOutput() {
        return new UAOutput();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "RequestBase")
    public JAXBElement<RequestBase> createRequestBase(RequestBase value) {
        return new JAXBElement<RequestBase>(_RequestBase_QNAME, RequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResponseBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ResponseBase")
    public JAXBElement<ResponseBase> createResponseBase(ResponseBase value) {
        return new JAXBElement<ResponseBase>(_ResponseBase_QNAME, ResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfError }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfError }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ArrayOfError")
    public JAXBElement<ArrayOfError> createArrayOfError(ArrayOfError value) {
        return new JAXBElement<ArrayOfError>(_ArrayOfError_QNAME, ArrayOfError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Error }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Error }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "Error")
    public JAXBElement<Error> createError(Error value) {
        return new JAXBElement<Error>(_Error_QNAME, Error.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountTransactionHistoryRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountTransactionHistoryRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "AccountTransactionHistoryRequest")
    public JAXBElement<AccountTransactionHistoryRequest> createAccountTransactionHistoryRequest(AccountTransactionHistoryRequest value) {
        return new JAXBElement<AccountTransactionHistoryRequest>(_AccountTransactionHistoryRequest_QNAME, AccountTransactionHistoryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountTransactionHistoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AccountTransactionHistoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "AccountTransactionHistoryResponse")
    public JAXBElement<AccountTransactionHistoryResponse> createAccountTransactionHistoryResponse(AccountTransactionHistoryResponse value) {
        return new JAXBElement<AccountTransactionHistoryResponse>(_AccountTransactionHistoryResponse_QNAME, AccountTransactionHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionHistoryInquiryRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionHistoryInquiryRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "TransactionHistoryInquiryRequest")
    public JAXBElement<TransactionHistoryInquiryRequest> createTransactionHistoryInquiryRequest(TransactionHistoryInquiryRequest value) {
        return new JAXBElement<TransactionHistoryInquiryRequest>(_TransactionHistoryInquiryRequest_QNAME, TransactionHistoryInquiryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionHistoryInquiryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionHistoryInquiryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "TransactionHistoryInquiryResponse")
    public JAXBElement<TransactionHistoryInquiryResponse> createTransactionHistoryInquiryResponse(TransactionHistoryInquiryResponse value) {
        return new JAXBElement<TransactionHistoryInquiryResponse>(_TransactionHistoryInquiryResponse_QNAME, TransactionHistoryInquiryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionRequestBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtensionRequestBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ExtensionRequestBase")
    public JAXBElement<ExtensionRequestBase> createExtensionRequestBase(ExtensionRequestBase value) {
        return new JAXBElement<ExtensionRequestBase>(_ExtensionRequestBase_QNAME, ExtensionRequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillPayHistoryRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BillPayHistoryRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "BillPayHistoryRequest")
    public JAXBElement<BillPayHistoryRequest> createBillPayHistoryRequest(BillPayHistoryRequest value) {
        return new JAXBElement<BillPayHistoryRequest>(_BillPayHistoryRequest_QNAME, BillPayHistoryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionResponseBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtensionResponseBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ExtensionResponseBase")
    public JAXBElement<ExtensionResponseBase> createExtensionResponseBase(ExtensionResponseBase value) {
        return new JAXBElement<ExtensionResponseBase>(_ExtensionResponseBase_QNAME, ExtensionResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfExtensionError }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfExtensionError }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ArrayOfExtensionError")
    public JAXBElement<ArrayOfExtensionError> createArrayOfExtensionError(ArrayOfExtensionError value) {
        return new JAXBElement<ArrayOfExtensionError>(_ArrayOfExtensionError_QNAME, ArrayOfExtensionError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionError }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtensionError }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ExtensionError")
    public JAXBElement<ExtensionError> createExtensionError(ExtensionError value) {
        return new JAXBElement<ExtensionError>(_ExtensionError_QNAME, ExtensionError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillPayHistoryResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BillPayHistoryResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "BillPayHistoryResponse")
    public JAXBElement<BillPayHistoryResponse> createBillPayHistoryResponse(BillPayHistoryResponse value) {
        return new JAXBElement<BillPayHistoryResponse>(_BillPayHistoryResponse_QNAME, BillPayHistoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionInput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionInput }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "TransactionInput")
    public JAXBElement<TransactionInput> createTransactionInput(TransactionInput value) {
        return new JAXBElement<TransactionInput>(_TransactionInput_QNAME, TransactionInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Input }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Input }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "Input")
    public JAXBElement<Input> createInput(Input value) {
        return new JAXBElement<Input>(_Input_QNAME, Input.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRequestBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfRequestBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ArrayOfRequestBase")
    public JAXBElement<ArrayOfRequestBase> createArrayOfRequestBase(ArrayOfRequestBase value) {
        return new JAXBElement<ArrayOfRequestBase>(_ArrayOfRequestBase_QNAME, ArrayOfRequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UAInput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UAInput }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "UAInput")
    public JAXBElement<UAInput> createUAInput(UAInput value) {
        return new JAXBElement<UAInput>(_UAInput_QNAME, UAInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionOutput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionOutput }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "TransactionOutput")
    public JAXBElement<TransactionOutput> createTransactionOutput(TransactionOutput value) {
        return new JAXBElement<TransactionOutput>(_TransactionOutput_QNAME, TransactionOutput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Output }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Output }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "Output")
    public JAXBElement<Output> createOutput(Output value) {
        return new JAXBElement<Output>(_Output_QNAME, Output.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfResponseBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfResponseBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ArrayOfResponseBase")
    public JAXBElement<ArrayOfResponseBase> createArrayOfResponseBase(ArrayOfResponseBase value) {
        return new JAXBElement<ArrayOfResponseBase>(_ArrayOfResponseBase_QNAME, ArrayOfResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UAOutput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UAOutput }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "UAOutput")
    public JAXBElement<UAOutput> createUAOutput(UAOutput value) {
        return new JAXBElement<UAOutput>(_UAOutput_QNAME, UAOutput.class, null, value);
    }

}
