//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import com.dep.integration.transaction.hook.fiserv.dto.jaxb.arrays.ArrayOfanyType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             Wrapper tag that identifies the following data that is used for Output from the Core API.
 *             </summary>
 * 
 * <p>Java class for Output complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Output"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExtensionResponses" type="{http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfanyType" minOccurs="0"/&gt;
 *         &lt;element name="Responses" type="{http://www.opensolutions.com/CoreApi}ArrayOfResponseBase" minOccurs="0"/&gt;
 *         &lt;element name="UserAuthentication" type="{http://www.opensolutions.com/CoreApi}UAOutput" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Output", propOrder = {
    "extensionResponses",
    "responses",
    "userAuthentication"
})
public class Output {

    @XmlElement(name = "ExtensionResponses", nillable = true)
    protected ArrayOfanyType extensionResponses;
    @XmlElement(name = "Responses", nillable = true)
    protected ArrayOfResponseBase responses;
    @XmlElement(name = "UserAuthentication", nillable = true)
    protected UAOutput userAuthentication;

    /**
     * Gets the value of the extensionResponses property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfanyType }
     *     
     */
    public ArrayOfanyType getExtensionResponses() {
        return extensionResponses;
    }

    /**
     * Sets the value of the extensionResponses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfanyType }
     *     
     */
    public void setExtensionResponses(ArrayOfanyType value) {
        this.extensionResponses = value;
    }

    /**
     * Gets the value of the responses property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfResponseBase }
     *     
     */
    public ArrayOfResponseBase getResponses() {
        return responses;
    }

    /**
     * Sets the value of the responses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfResponseBase }
     *     
     */
    public void setResponses(ArrayOfResponseBase value) {
        this.responses = value;
    }

    /**
     * Gets the value of the userAuthentication property.
     * 
     * @return
     *     possible object is
     *     {@link UAOutput }
     *     
     */
    public UAOutput getUserAuthentication() {
        return userAuthentication;
    }

    /**
     * Sets the value of the userAuthentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link UAOutput }
     *     
     */
    public void setUserAuthentication(UAOutput value) {
        this.userAuthentication = value;
    }

}
