//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.31 at 03:26:52 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SubmitRequestResult" type="{http://www.opensolutions.com/CoreApi}TransactionOutput" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "submitRequestResult"
})
@XmlRootElement(name = "SubmitRequestResponse")
public class SubmitRequestResponse {

    @XmlElement(name = "SubmitRequestResult", nillable = true)
    protected TransactionOutput submitRequestResult;

    /**
     * Gets the value of the submitRequestResult property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionOutput }
     *     
     */
    public TransactionOutput getSubmitRequestResult() {
        return submitRequestResult;
    }

    /**
     * Sets the value of the submitRequestResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionOutput }
     *     
     */
    public void setSubmitRequestResult(TransactionOutput value) {
        this.submitRequestResult = value;
    }

}
