//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             This transaction returns transaction history information for the account and other criteria specified
 *             </summary>
 * 
 * <p>Java class for TransactionHistoryInquiryRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionHistoryInquiryRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opensolutions.com/CoreApi}RequestBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="FromDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="IsCustomerView" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsIncludeFunds" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsOnlyComplete" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SearchDateOption" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="ThruDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="TransactionSourceCodes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionHistoryInquiryRequest", propOrder = {
    "accountNumber",
    "fromDate",
    "isCustomerView",
    "isIncludeFunds",
    "isOnlyComplete",
    "searchDateOption",
    "thruDate",
    "transactionSourceCodes"
})
public class TransactionHistoryInquiryRequest
    extends RequestBase
{

    @XmlElement(name = "AccountNumber", nillable = true)
    protected Long accountNumber;
    @XmlElement(name = "FromDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fromDate;
    @XmlElement(name = "IsCustomerView", nillable = true)
    protected Boolean isCustomerView;
    @XmlElement(name = "IsIncludeFunds", nillable = true)
    protected Boolean isIncludeFunds;
    @XmlElement(name = "IsOnlyComplete", nillable = true)
    protected Boolean isOnlyComplete;
    @XmlElement(name = "SearchDateOption", nillable = true)
    protected Integer searchDateOption;
    @XmlElement(name = "ThruDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar thruDate;
    @XmlElement(name = "TransactionSourceCodes", nillable = true)
    protected String transactionSourceCodes;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountNumber(Long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the isCustomerView property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCustomerView() {
        return isCustomerView;
    }

    /**
     * Sets the value of the isCustomerView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCustomerView(Boolean value) {
        this.isCustomerView = value;
    }

    /**
     * Gets the value of the isIncludeFunds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsIncludeFunds() {
        return isIncludeFunds;
    }

    /**
     * Sets the value of the isIncludeFunds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsIncludeFunds(Boolean value) {
        this.isIncludeFunds = value;
    }

    /**
     * Gets the value of the isOnlyComplete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsOnlyComplete() {
        return isOnlyComplete;
    }

    /**
     * Sets the value of the isOnlyComplete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsOnlyComplete(Boolean value) {
        this.isOnlyComplete = value;
    }

    /**
     * Gets the value of the searchDateOption property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSearchDateOption() {
        return searchDateOption;
    }

    /**
     * Sets the value of the searchDateOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSearchDateOption(Integer value) {
        this.searchDateOption = value;
    }

    /**
     * Gets the value of the thruDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getThruDate() {
        return thruDate;
    }

    /**
     * Sets the value of the thruDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setThruDate(XMLGregorianCalendar value) {
        this.thruDate = value;
    }

    /**
     * Gets the value of the transactionSourceCodes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSourceCodes() {
        return transactionSourceCodes;
    }

    /**
     * Sets the value of the transactionSourceCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSourceCodes(String value) {
        this.transactionSourceCodes = value;
    }

}
