//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             Wrapper tag that identifies if the request was successful and if not, a collection of one or more Errors.
 *             </summary>
 * 
 * <p>Java class for UAOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UAOutput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Errors" type="{http://www.opensolutions.com/CoreApi}ArrayOfError" minOccurs="0"/&gt;
 *         &lt;element name="PersNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WasSuccessful" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UAOutput", propOrder = {
    "errors",
    "persNbr",
    "wasSuccessful"
})
public class UAOutput {

    @XmlElement(name = "Errors", nillable = true)
    protected ArrayOfError errors;
    @XmlElement(name = "PersNbr", nillable = true)
    protected String persNbr;
    @XmlElement(name = "WasSuccessful", nillable = true)
    protected Boolean wasSuccessful;

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfError }
     *     
     */
    public ArrayOfError getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfError }
     *     
     */
    public void setErrors(ArrayOfError value) {
        this.errors = value;
    }

    /**
     * Gets the value of the persNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersNbr() {
        return persNbr;
    }

    /**
     * Sets the value of the persNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersNbr(String value) {
        this.persNbr = value;
    }

    /**
     * Gets the value of the wasSuccessful property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWasSuccessful() {
        return wasSuccessful;
    }

    /**
     * Sets the value of the wasSuccessful property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWasSuccessful(Boolean value) {
        this.wasSuccessful = value;
    }

}
