<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages">
  <xs:complexType name="ArrayOfRtxn">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Rtxn" nillable="true" type="tns:Rtxn"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfRtxn" nillable="true" type="tns:ArrayOfRtxn"/>
  <xs:complexType name="Rtxn">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation><![CDATA[<summary>
            A specific transaction record for the account.
            </summary>
            <remarks>This class is used by the <see cref="T:AccountTransactionHistoryResponse" /> class.</remarks>
            <tocexclude />]]></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="AccountNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA AcctNbr on the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ActivityDateTime" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Activity Date Time for this transaction.Format is MM/DD/YYYY HH:MI:SS.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ApprovingPersonName" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the full name of the approving person.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ApprovingPersonNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the person number for the approving person for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="CheckNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Check number for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="CurrentRtxnStatisticsCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the current transaction status code.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="CurrentRtxnStatisticsDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the status code description.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="DebitCredit" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            D = Debit, C = Credit.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="EffectiveDate" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Effective Date for this transaction.Format is MM/DD/YYYY.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ExchTxnGrp" nillable="true" type="tns:ArrayOfExchTxn">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Available for use with DNA version 4.1 and higher.
            This will return the Multicurrency Foreign Exchange Transaction infor if associated with the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ExternalRtxnDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the external description for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ExternalRtxnDescriptionNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA external description number for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="HoldAccountNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Hold Account number for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ImageID" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Image Id for this transaction. Supports an alphnumeric value.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="InternalRtxnDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the internal description for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="InternalRtxnDescriptionNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA internal description number for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="IsCustomerView" nillable="true" type="xs:boolean">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Providing the ability to display all transactions in the transaction history 
            irrespective of customer view indicator on the RTXNTYP is set to Y or N for employees/teller . Default is Y.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="IsRecurring" nillable="true" type="xs:boolean">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            RecurringYN
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="IsReversal" nillable="true" type="xs:boolean">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Indicates whether the transaction is reversal.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="OriginatingPersonName" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the full name of the originating person.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="OriginatingPersonNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the person number for the originating person for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ParentAccountNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The DNA Account number of the parent transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ParentRtxnNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The DNA RTXN number of the parent transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="PostDate" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Post Date for this transaction.Format is MM/DD/YYYY.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="PriorAvailableBalance" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Prior Available balance stored. This is applicable to deposit accounts only.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RtxnNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA RTXN number for the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RtxnReasonCd" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
             Identifies the reason the transaction is processed.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RtxnSourceCatCd" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the RTXN source category code for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RtxnSourceCd" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the RTXN source code for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RtxnTypeCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA RTXN type code for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RtxnTypeDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the RTXN type code description for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RunningBalance" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Running balance or Resulting balance after the transaction is posted. Not returned if either the account is masterline or TransactionReferenceNbr is supplied. Returned when either:
            (1) FromDate, ThruDate are the ONLY criteria supplied, SortBy is set to null or TIMEUNIQUEEXTN, or
            (2) If ResultingBalYN is set to Y in request and FromDate is supplied.
            Note that calculation of Resulting Balance under arbitrary sort and filter criteria could result in higher computation overhead.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="SpreadDetails" nillable="true" type="tns:ArrayOfSpreadDetail">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            This will return transaction balance detail
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="StandardIndustryClassCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value represents the Standard Industry  Classification code for the Acquirer
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="StandardIndustrySubClassCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
             Tag value represents the Extended classification for the Standard Classification code for the Acquirer
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TimeUniqueExtension" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the time unique extension from which to start the query.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TraceId" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Trace Id for this transaction. Supports an alphnumeric value and should be used instead of the Trace Number property.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TraceNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Depricated - Use Trace Id instead which supports an alphanumeric value. Trace number for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionAmount" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The transaction amount.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionAuxNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            RtxnAuxNbr for transaction
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionReferenceNumber" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            AcctNbr-RtxnNbr
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="WaiveApprPersNbr" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
             Person who approved the waiving of a loan related fee/charge.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Rtxn" nillable="true" type="tns:Rtxn"/>
  <xs:complexType name="ArrayOfExchTxn">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="ExchTxn" nillable="true" type="tns:ExchTxn"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfExchTxn" nillable="true" type="tns:ArrayOfExchTxn"/>
  <xs:complexType name="ExchTxn">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            Available for use with DNA version 4.1 and higher.
            This will return the Multicurrency Foreign Exchange Transaction infor if associated with the transaction
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="ExchangeRate" nillable="true" type="xs:decimal">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Available for use with DNA version 4.1 and higher.
            Attribute used only for multi-currency transfers.  This is the final exchange rate.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="OtherAmount" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Available for use with DNA version 4.1 and higher.
            This returns the amount in other Currency
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="OtherCCY" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Available for use with DNA version 4.1 and higher.
            This returns the other Currency Code.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ExchTxn" nillable="true" type="tns:ExchTxn"/>
  <xs:complexType name="ArrayOfSpreadDetail">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="SpreadDetail" nillable="true" type="tns:SpreadDetail"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfSpreadDetail" nillable="true" type="tns:ArrayOfSpreadDetail"/>
  <xs:complexType name="SpreadDetail">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation><![CDATA[<summary>
            Represents the individual detail for a specific account transaction.
            </summary>
            <remarks>This class is used by the <see cref="T:TransactionResponse" /> class.</remarks>
            <tocexclude />]]></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="Amount" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The dollar amount applied to this balance type.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="BalanceCategoryCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the balance category code.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="BalanceTypeCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the balance type code.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Description" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The concatenation of the balance category description, a space, and the balance type description.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="SpreadDetail" nillable="true" type="tns:SpreadDetail"/>
  <xs:complexType name="ArrayOfTransaction">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Transaction" nillable="true" type="tns:Transaction"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfTransaction" nillable="true" type="tns:ArrayOfTransaction"/>
  <xs:complexType name="Transaction">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation><![CDATA[<summary>
            A specific transaction record for the account.
            </summary>
            <remarks>This class is used by the <see cref="T:TransactionHistoryInquiryResponse" /> class.</remarks>
            <tocexclude />]]></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="ActivityDateTime" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the Date the transaction was processed. Format is MM/DD/YYYY HH:MI:SS.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="BalanceTypes" nillable="true" type="tns:ArrayOfTransactionBalanceType">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Balance Types for account
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="CheckNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Check number for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="CurrentTransactionStatus" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the Current status of the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="EffectiveDate" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the Date the transaction took effect. Format is MM/DD/YYYY.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ExternalTransactionDescription" nillable="true" type="tns:ExtRtxnDescription">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the external description for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="Funds" nillable="true" type="tns:ArrayOfFundAmountDetail">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the Core Fund Type code of the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="InternalTransactionDescription" nillable="true" type="tns:IntRtxnDescription">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the internal description for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="IsCustomerView" nillable="true" type="xs:boolean">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Indicates whether the transaction is a customer view transaction in the RTXNTYP table.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="PostDate" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the date the transaction was posted. Format is MM/DD/YYYY.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TimeUniqueExtension" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The Time Unique Extension Number is a system assigned key. Manages transaction concurrency.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionAmount" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The transaction amount.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the DNA Rtxn number for the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionReferenceNumber" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Unique transaction reference number assigned by the system to facilitate tracking of the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionSourceCategoryCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the RTXN source category code for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionSourceCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the RTXN source code for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionTypeCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the Code of the transaction type from the RtxnTyp system table.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionTypeDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Tag value contains the RTXN type code description for this transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Transaction" nillable="true" type="tns:Transaction"/>
  <xs:complexType name="ArrayOfTransactionBalanceType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="TransactionBalanceType" nillable="true" type="tns:TransactionBalanceType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfTransactionBalanceType" nillable="true" type="tns:ArrayOfTransactionBalanceType"/>
  <xs:complexType name="TransactionBalanceType">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            Balance Type record for the account.
            &lt;remarks>This class is used by the &lt;see cref="T:Transaction" /> class.&lt;/remarks>
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="Amount" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies Monetary amount that affects the balance. Negative amounts reduce their associated balances.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="BalanceTypeDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the Description of the balance that was affected by the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RunningBalance" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the amount of the remaining balance after the transaction was processed. Available for Note Balance, Escrow Balance, and Operating Fund Balance.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="SubAccountNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the Sub-account number for Balance Category / Balance Type.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TransactionDueDate" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the date the payment was due. If there is no due date for the transaction, this field will be blank.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="TransactionBalanceType" nillable="true" type="tns:TransactionBalanceType"/>
  <xs:complexType name="ExtRtxnDescription">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            External Transaction Description.
            &lt;remarks>This class is used by the &lt;see cref="T:Transaction" /> class.&lt;/remarks>
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="ExternalTransactionDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            . The status attribute identifies the current status of the official check.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="ExternalTransactionDescriptionNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Check number assigned to the official check.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ExtRtxnDescription" nillable="true" type="tns:ExtRtxnDescription"/>
  <xs:complexType name="ArrayOfFundAmountDetail">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="FundAmountDetail" nillable="true" type="tns:FundAmountDetail"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="ArrayOfFundAmountDetail" nillable="true" type="tns:ArrayOfFundAmountDetail"/>
  <xs:complexType name="FundAmountDetail">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            Wrapper tag for the funds used in the transaction
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="ClearCategoryCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA clearing category code that identifies the clear category for the funds in the transaction. 
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="FundAmount" nillable="true" type="xs:double">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the Fund Amount used in the transaction
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="FundTypeCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA Fund Type code of the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="FundTypeDetailCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the DNA Fund Type Detail Code that identifies the detail of the funds in the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="SequenceNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute is a system assigned number that identifies the sequence of the transaction.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="TotalNumberOfItems" nillable="true" type="xs:int">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Attribute identifies the number of physical check items provided by the customer. 
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="FundAmountDetail" nillable="true" type="tns:FundAmountDetail"/>
  <xs:complexType name="IntRtxnDescription">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            Internal Transaction Description.
            &lt;remarks>This class is used by the &lt;see cref="T:Transaction" /> class.&lt;/remarks>
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="InternalTransactionDescription" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            The status attribute identifies the current status of the official check.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="InternalTransactionDescriptionNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Check number assigned to the official check.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="IntRtxnDescription" nillable="true" type="tns:IntRtxnDescription"/>
</xs:schema>
