<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages.AccountBalanceVariableMaintenance.Response" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages.AccountBalanceVariableMaintenance.Response">
  <xs:complexType name="AccountBalanceVariableMaintenanceResponseAccount">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            Response account information.
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="AccountNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Identifies the account number that was maintained.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="AccountSubAccountCalculationVariable" nillable="true" type="tns:AccountSubAccountCalculationVariableResponse">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            SubAccount number that was maintained.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="SubAccountNumber" nillable="true" type="xs:long">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            SubAccount number that was maintained.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="AccountBalanceVariableMaintenanceResponseAccount" nillable="true" type="tns:AccountBalanceVariableMaintenanceResponseAccount"/>
  <xs:complexType name="AccountSubAccountCalculationVariableResponse">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            Account sub account calculation variable wrapper.
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="IsSuccess" nillable="true" type="xs:boolean">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Was the maintenance successful.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="AccountSubAccountCalculationVariableResponse" nillable="true" type="tns:AccountSubAccountCalculationVariableResponse"/>
</xs:schema>