<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages.OpenSolutions.CoreApiService.Services.Messages.AccountMaintenance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages.OpenSolutions.CoreApiService.Services.Messages.AccountMaintenance">
  <xs:complexType name="AccountRiskRating">
    <xs:annotation>
      <xs:appinfo/>
      <xs:documentation>&lt;summary>
            This class is used to maintain account risk ratings 
            &lt;/summary></xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element minOccurs="0" name="EffectiveDate" nillable="true" type="xs:dateTime">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            Date when risk rating is effective.
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element minOccurs="0" name="RiskRatingCode" nillable="true" type="xs:string">
        <xs:annotation>
          <xs:appinfo/>
          <xs:documentation>&lt;summary>
            risk rating code 
            &lt;/summary></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="AccountRiskRating" nillable="true" type="tns:AccountRiskRating"/>
</xs:schema>