//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.31 at 03:26:52 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.billpayhistory;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dep.integration.transaction.hook.fiserv.dto.jaxb.billpayhistory package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArrayOfBillPayment_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", "ArrayOfBillPayment");
    private final static QName _BillPayment_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", "BillPayment");
    private final static QName _ArrayOfTransaction_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", "ArrayOfTransaction");
    private final static QName _Transaction_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", "Transaction");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dep.integration.transaction.hook.fiserv.dto.jaxb.billpayhistory
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfBillPayment }
     * 
     */
    public ArrayOfBillPayment createArrayOfBillPayment() {
        return new ArrayOfBillPayment();
    }

    /**
     * Create an instance of {@link BillPayment }
     * 
     */
    public BillPayment createBillPayment() {
        return new BillPayment();
    }

    /**
     * Create an instance of {@link ArrayOfTransaction }
     * 
     */
    public ArrayOfTransaction createArrayOfTransaction() {
        return new ArrayOfTransaction();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfBillPayment }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfBillPayment }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", name = "ArrayOfBillPayment")
    public JAXBElement<ArrayOfBillPayment> createArrayOfBillPayment(ArrayOfBillPayment value) {
        return new JAXBElement<ArrayOfBillPayment>(_ArrayOfBillPayment_QNAME, ArrayOfBillPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillPayment }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BillPayment }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", name = "BillPayment")
    public JAXBElement<BillPayment> createBillPayment(BillPayment value) {
        return new JAXBElement<BillPayment>(_BillPayment_QNAME, BillPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTransaction }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfTransaction }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", name = "ArrayOfTransaction")
    public JAXBElement<ArrayOfTransaction> createArrayOfTransaction(ArrayOfTransaction value) {
        return new JAXBElement<ArrayOfTransaction>(_ArrayOfTransaction_QNAME, ArrayOfTransaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transaction }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Transaction }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayHistory", name = "Transaction")
    public JAXBElement<Transaction> createTransaction(Transaction value) {
        return new JAXBElement<Transaction>(_Transaction_QNAME, Transaction.class, null, value);
    }

}
