//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.billpaymaintenance;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ArrayOfBillPayAllotments complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="ArrayOfBillPayAllotments"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BillPayAllotments" type="{http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance}BillPayAllotments" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfBillPayAllotments", propOrder = {
    "billPayAllotments"
})
public class ArrayOfBillPayAllotments {

    @XmlElement(name = "BillPayAllotments", nillable = true)
    protected List<BillPayAllotments> billPayAllotments;

    /**
     * Gets the value of the billPayAllotments property.
     * 
     * <p>This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the jakarta XML Binding object.
     * This is why there is not a {@code set} method for the billPayAllotments property.</p>
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * </p>
     * <pre>
     * getBillPayAllotments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BillPayAllotments }
     * </p>
     * 
     * 
     * @return
     *     The value of the billPayAllotments property.
     */
    public List<BillPayAllotments> getBillPayAllotments() {
        if (billPayAllotments == null) {
            billPayAllotments = new ArrayList<>();
        }
        return this.billPayAllotments;
    }

}
