//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.billpaymaintenance;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for CRATaxPayment complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="CRATaxPayment"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AdjustedGSTAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="ArrearsAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="AuditAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="BillPayCRATaxPaymentTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContactName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContactPhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ContactTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EmployeeCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="FileDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="FiscalEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="GrossPayroll" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="InputTaxCredit" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="InstallmentAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="InstallmentPaid" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NetTaxRemittance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="NewHousingGSTRebateAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="OnFileAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="OtherPayments" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="PayerName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="PeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PropertyTax" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="RebateAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="SalesOtherRevenue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="TaxTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TaxableSupplies" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRATaxPayment", propOrder = {
    "adjustedGSTAmount",
    "arrearsAmount",
    "auditAmount",
    "billPayCRATaxPaymentTypeCode",
    "contactName",
    "contactPhoneNumber",
    "contactTitle",
    "employeeCount",
    "fileDate",
    "fiscalEndDate",
    "grossPayroll",
    "inputTaxCredit",
    "installmentAmount",
    "installmentPaid",
    "language",
    "netTaxRemittance",
    "newHousingGSTRebateAmount",
    "onFileAmount",
    "otherPayments",
    "payerName",
    "periodEndDate",
    "periodStartDate",
    "propertyTax",
    "rebateAmount",
    "salesOtherRevenue",
    "taxTypeCode",
    "taxableSupplies"
})
public class CRATaxPayment {

    @XmlElement(name = "AdjustedGSTAmount", nillable = true)
    protected Double adjustedGSTAmount;
    @XmlElement(name = "ArrearsAmount", nillable = true)
    protected Double arrearsAmount;
    @XmlElement(name = "AuditAmount", nillable = true)
    protected Double auditAmount;
    @XmlElement(name = "BillPayCRATaxPaymentTypeCode", nillable = true)
    protected String billPayCRATaxPaymentTypeCode;
    @XmlElement(name = "ContactName", nillable = true)
    protected String contactName;
    @XmlElement(name = "ContactPhoneNumber", nillable = true)
    protected String contactPhoneNumber;
    @XmlElement(name = "ContactTitle", nillable = true)
    protected String contactTitle;
    @XmlElement(name = "EmployeeCount", nillable = true)
    protected Integer employeeCount;
    @XmlElement(name = "FileDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fileDate;
    @XmlElement(name = "FiscalEndDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fiscalEndDate;
    @XmlElement(name = "GrossPayroll", nillable = true)
    protected Double grossPayroll;
    @XmlElement(name = "InputTaxCredit", nillable = true)
    protected Double inputTaxCredit;
    @XmlElement(name = "InstallmentAmount", nillable = true)
    protected Double installmentAmount;
    @XmlElement(name = "InstallmentPaid", nillable = true)
    protected Double installmentPaid;
    @XmlElement(name = "Language", nillable = true)
    protected String language;
    @XmlElement(name = "NetTaxRemittance", nillable = true)
    protected Double netTaxRemittance;
    @XmlElement(name = "NewHousingGSTRebateAmount", nillable = true)
    protected Double newHousingGSTRebateAmount;
    @XmlElement(name = "OnFileAmount", nillable = true)
    protected Double onFileAmount;
    @XmlElement(name = "OtherPayments", nillable = true)
    protected Double otherPayments;
    @XmlElement(name = "PayerName", nillable = true)
    protected String payerName;
    @XmlElement(name = "PeriodEndDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodEndDate;
    @XmlElement(name = "PeriodStartDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar periodStartDate;
    @XmlElement(name = "PropertyTax", nillable = true)
    protected Double propertyTax;
    @XmlElement(name = "RebateAmount", nillable = true)
    protected Double rebateAmount;
    @XmlElement(name = "SalesOtherRevenue", nillable = true)
    protected Double salesOtherRevenue;
    @XmlElement(name = "TaxTypeCode", nillable = true)
    protected String taxTypeCode;
    @XmlElement(name = "TaxableSupplies", nillable = true)
    protected Double taxableSupplies;

    /**
     * Gets the value of the adjustedGSTAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAdjustedGSTAmount() {
        return adjustedGSTAmount;
    }

    /**
     * Sets the value of the adjustedGSTAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAdjustedGSTAmount(Double value) {
        this.adjustedGSTAmount = value;
    }

    /**
     * Gets the value of the arrearsAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getArrearsAmount() {
        return arrearsAmount;
    }

    /**
     * Sets the value of the arrearsAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setArrearsAmount(Double value) {
        this.arrearsAmount = value;
    }

    /**
     * Gets the value of the auditAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAuditAmount() {
        return auditAmount;
    }

    /**
     * Sets the value of the auditAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAuditAmount(Double value) {
        this.auditAmount = value;
    }

    /**
     * Gets the value of the billPayCRATaxPaymentTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillPayCRATaxPaymentTypeCode() {
        return billPayCRATaxPaymentTypeCode;
    }

    /**
     * Sets the value of the billPayCRATaxPaymentTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillPayCRATaxPaymentTypeCode(String value) {
        this.billPayCRATaxPaymentTypeCode = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the contactPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhoneNumber() {
        return contactPhoneNumber;
    }

    /**
     * Sets the value of the contactPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhoneNumber(String value) {
        this.contactPhoneNumber = value;
    }

    /**
     * Gets the value of the contactTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactTitle() {
        return contactTitle;
    }

    /**
     * Sets the value of the contactTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactTitle(String value) {
        this.contactTitle = value;
    }

    /**
     * Gets the value of the employeeCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEmployeeCount() {
        return employeeCount;
    }

    /**
     * Sets the value of the employeeCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEmployeeCount(Integer value) {
        this.employeeCount = value;
    }

    /**
     * Gets the value of the fileDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileDate() {
        return fileDate;
    }

    /**
     * Sets the value of the fileDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileDate(XMLGregorianCalendar value) {
        this.fileDate = value;
    }

    /**
     * Gets the value of the fiscalEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFiscalEndDate() {
        return fiscalEndDate;
    }

    /**
     * Sets the value of the fiscalEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFiscalEndDate(XMLGregorianCalendar value) {
        this.fiscalEndDate = value;
    }

    /**
     * Gets the value of the grossPayroll property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getGrossPayroll() {
        return grossPayroll;
    }

    /**
     * Sets the value of the grossPayroll property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setGrossPayroll(Double value) {
        this.grossPayroll = value;
    }

    /**
     * Gets the value of the inputTaxCredit property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInputTaxCredit() {
        return inputTaxCredit;
    }

    /**
     * Sets the value of the inputTaxCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInputTaxCredit(Double value) {
        this.inputTaxCredit = value;
    }

    /**
     * Gets the value of the installmentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInstallmentAmount() {
        return installmentAmount;
    }

    /**
     * Sets the value of the installmentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInstallmentAmount(Double value) {
        this.installmentAmount = value;
    }

    /**
     * Gets the value of the installmentPaid property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getInstallmentPaid() {
        return installmentPaid;
    }

    /**
     * Sets the value of the installmentPaid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setInstallmentPaid(Double value) {
        this.installmentPaid = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the netTaxRemittance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNetTaxRemittance() {
        return netTaxRemittance;
    }

    /**
     * Sets the value of the netTaxRemittance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNetTaxRemittance(Double value) {
        this.netTaxRemittance = value;
    }

    /**
     * Gets the value of the newHousingGSTRebateAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNewHousingGSTRebateAmount() {
        return newHousingGSTRebateAmount;
    }

    /**
     * Sets the value of the newHousingGSTRebateAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNewHousingGSTRebateAmount(Double value) {
        this.newHousingGSTRebateAmount = value;
    }

    /**
     * Gets the value of the onFileAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOnFileAmount() {
        return onFileAmount;
    }

    /**
     * Sets the value of the onFileAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOnFileAmount(Double value) {
        this.onFileAmount = value;
    }

    /**
     * Gets the value of the otherPayments property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOtherPayments() {
        return otherPayments;
    }

    /**
     * Sets the value of the otherPayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOtherPayments(Double value) {
        this.otherPayments = value;
    }

    /**
     * Gets the value of the payerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerName() {
        return payerName;
    }

    /**
     * Sets the value of the payerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerName(String value) {
        this.payerName = value;
    }

    /**
     * Gets the value of the periodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodEndDate() {
        return periodEndDate;
    }

    /**
     * Sets the value of the periodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodEndDate(XMLGregorianCalendar value) {
        this.periodEndDate = value;
    }

    /**
     * Gets the value of the periodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPeriodStartDate() {
        return periodStartDate;
    }

    /**
     * Sets the value of the periodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPeriodStartDate(XMLGregorianCalendar value) {
        this.periodStartDate = value;
    }

    /**
     * Gets the value of the propertyTax property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPropertyTax() {
        return propertyTax;
    }

    /**
     * Sets the value of the propertyTax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPropertyTax(Double value) {
        this.propertyTax = value;
    }

    /**
     * Gets the value of the rebateAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRebateAmount() {
        return rebateAmount;
    }

    /**
     * Sets the value of the rebateAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRebateAmount(Double value) {
        this.rebateAmount = value;
    }

    /**
     * Gets the value of the salesOtherRevenue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSalesOtherRevenue() {
        return salesOtherRevenue;
    }

    /**
     * Sets the value of the salesOtherRevenue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSalesOtherRevenue(Double value) {
        this.salesOtherRevenue = value;
    }

    /**
     * Gets the value of the taxTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxTypeCode() {
        return taxTypeCode;
    }

    /**
     * Sets the value of the taxTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxTypeCode(String value) {
        this.taxTypeCode = value;
    }

    /**
     * Gets the value of the taxableSupplies property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTaxableSupplies() {
        return taxableSupplies;
    }

    /**
     * Sets the value of the taxableSupplies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTaxableSupplies(Double value) {
        this.taxableSupplies = value;
    }

}
