//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.billpaymaintenance;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.datacontract.schemas._2004._07.coreapiextension_messages package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ArrayOfBillPayAllotments_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", "ArrayOfBillPayAllotments");
    private static final QName _BillPayAllotments_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", "BillPayAllotments");
    private static final QName _CRATaxPayment_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", "CRATaxPayment");
    private static final QName _ArrayOfBillPaymentResponseAllotments_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", "ArrayOfBillPaymentResponseAllotments");
    private static final QName _BillPaymentResponseAllotments_QNAME = new QName("http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", "BillPaymentResponseAllotments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.datacontract.schemas._2004._07.coreapiextension_messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfBillPayAllotments }
     * 
     * @return
     *     the new instance of {@link ArrayOfBillPayAllotments }
     */
    public ArrayOfBillPayAllotments createArrayOfBillPayAllotments() {
        return new ArrayOfBillPayAllotments();
    }

    /**
     * Create an instance of {@link BillPayAllotments }
     * 
     * @return
     *     the new instance of {@link BillPayAllotments }
     */
    public BillPayAllotments createBillPayAllotments() {
        return new BillPayAllotments();
    }

    /**
     * Create an instance of {@link CRATaxPayment }
     * 
     * @return
     *     the new instance of {@link CRATaxPayment }
     */
    public CRATaxPayment createCRATaxPayment() {
        return new CRATaxPayment();
    }

    /**
     * Create an instance of {@link ArrayOfBillPaymentResponseAllotments }
     * 
     * @return
     *     the new instance of {@link ArrayOfBillPaymentResponseAllotments }
     */
    public ArrayOfBillPaymentResponseAllotments createArrayOfBillPaymentResponseAllotments() {
        return new ArrayOfBillPaymentResponseAllotments();
    }

    /**
     * Create an instance of {@link BillPaymentResponseAllotments }
     * 
     * @return
     *     the new instance of {@link BillPaymentResponseAllotments }
     */
    public BillPaymentResponseAllotments createBillPaymentResponseAllotments() {
        return new BillPaymentResponseAllotments();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfBillPayAllotments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfBillPayAllotments }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", name = "ArrayOfBillPayAllotments")
    public JAXBElement<ArrayOfBillPayAllotments> createArrayOfBillPayAllotments(ArrayOfBillPayAllotments value) {
        return new JAXBElement<>(_ArrayOfBillPayAllotments_QNAME, ArrayOfBillPayAllotments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillPayAllotments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BillPayAllotments }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", name = "BillPayAllotments")
    public JAXBElement<BillPayAllotments> createBillPayAllotments(BillPayAllotments value) {
        return new JAXBElement<>(_BillPayAllotments_QNAME, BillPayAllotments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CRATaxPayment }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CRATaxPayment }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", name = "CRATaxPayment")
    public JAXBElement<CRATaxPayment> createCRATaxPayment(CRATaxPayment value) {
        return new JAXBElement<>(_CRATaxPayment_QNAME, CRATaxPayment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfBillPaymentResponseAllotments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfBillPaymentResponseAllotments }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", name = "ArrayOfBillPaymentResponseAllotments")
    public JAXBElement<ArrayOfBillPaymentResponseAllotments> createArrayOfBillPaymentResponseAllotments(ArrayOfBillPaymentResponseAllotments value) {
        return new JAXBElement<>(_ArrayOfBillPaymentResponseAllotments_QNAME, ArrayOfBillPaymentResponseAllotments.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillPaymentResponseAllotments }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BillPaymentResponseAllotments }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance", name = "BillPaymentResponseAllotments")
    public JAXBElement<BillPaymentResponseAllotments> createBillPaymentResponseAllotments(BillPaymentResponseAllotments value) {
        return new JAXBElement<>(_BillPaymentResponseAllotments_QNAME, BillPaymentResponseAllotments.class, null, value);
    }

}
