//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             External Transaction Description.
 *             <remarks>This class is used by the <see cref="T:Transaction" /> class.</remarks>
 *             </summary>
 * 
 * <p>Java class for ExtRtxnDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtRtxnDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExternalTransactionDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExternalTransactionDescriptionNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtRtxnDescription", propOrder = {
    "externalTransactionDescription",
    "externalTransactionDescriptionNumber"
})
public class ExtRtxnDescription {

    @XmlElement(name = "ExternalTransactionDescription", nillable = true)
    protected String externalTransactionDescription;
    @XmlElement(name = "ExternalTransactionDescriptionNumber", nillable = true)
    protected Long externalTransactionDescriptionNumber;

    /**
     * Gets the value of the externalTransactionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalTransactionDescription() {
        return externalTransactionDescription;
    }

    /**
     * Sets the value of the externalTransactionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalTransactionDescription(String value) {
        this.externalTransactionDescription = value;
    }

    /**
     * Gets the value of the externalTransactionDescriptionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExternalTransactionDescriptionNumber() {
        return externalTransactionDescriptionNumber;
    }

    /**
     * Sets the value of the externalTransactionDescriptionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExternalTransactionDescriptionNumber(Long value) {
        this.externalTransactionDescriptionNumber = value;
    }

}
