//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             Wrapper tag for the funds used in the transaction
 *             </summary>
 * 
 * <p>Java class for FundAmountDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FundAmountDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClearCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FundAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="FundTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FundTypeDetailCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SequenceNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="TotalNumberOfItems" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FundAmountDetail", propOrder = {
    "clearCategoryCode",
    "fundAmount",
    "fundTypeCode",
    "fundTypeDetailCode",
    "sequenceNumber",
    "totalNumberOfItems"
})
public class FundAmountDetail {

    @XmlElement(name = "ClearCategoryCode", nillable = true)
    protected String clearCategoryCode;
    @XmlElement(name = "FundAmount", nillable = true)
    protected Double fundAmount;
    @XmlElement(name = "FundTypeCode", nillable = true)
    protected String fundTypeCode;
    @XmlElement(name = "FundTypeDetailCode", nillable = true)
    protected String fundTypeDetailCode;
    @XmlElement(name = "SequenceNumber", nillable = true)
    protected Long sequenceNumber;
    @XmlElement(name = "TotalNumberOfItems", nillable = true)
    protected Integer totalNumberOfItems;

    /**
     * Gets the value of the clearCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClearCategoryCode() {
        return clearCategoryCode;
    }

    /**
     * Sets the value of the clearCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClearCategoryCode(String value) {
        this.clearCategoryCode = value;
    }

    /**
     * Gets the value of the fundAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFundAmount() {
        return fundAmount;
    }

    /**
     * Sets the value of the fundAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFundAmount(Double value) {
        this.fundAmount = value;
    }

    /**
     * Gets the value of the fundTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundTypeCode() {
        return fundTypeCode;
    }

    /**
     * Sets the value of the fundTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundTypeCode(String value) {
        this.fundTypeCode = value;
    }

    /**
     * Gets the value of the fundTypeDetailCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFundTypeDetailCode() {
        return fundTypeDetailCode;
    }

    /**
     * Sets the value of the fundTypeDetailCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFundTypeDetailCode(String value) {
        this.fundTypeDetailCode = value;
    }

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSequenceNumber(Long value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the totalNumberOfItems property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalNumberOfItems() {
        return totalNumberOfItems;
    }

    /**
     * Sets the value of the totalNumberOfItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalNumberOfItems(Integer value) {
        this.totalNumberOfItems = value;
    }

}
