//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.31 at 03:26:52 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             Internal Transaction Description.
 *             <remarks>This class is used by the <see cref="T:Transaction" /> class.</remarks>
 *             </summary>
 * 
 * <p>Java class for IntRtxnDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntRtxnDescription"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InternalTransactionDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InternalTransactionDescriptionNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntRtxnDescription", propOrder = {
    "internalTransactionDescription",
    "internalTransactionDescriptionNumber"
})
public class IntRtxnDescription {

    @XmlElement(name = "InternalTransactionDescription", nillable = true)
    protected String internalTransactionDescription;
    @XmlElement(name = "InternalTransactionDescriptionNumber", nillable = true)
    protected Long internalTransactionDescriptionNumber;

    /**
     * Gets the value of the internalTransactionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalTransactionDescription() {
        return internalTransactionDescription;
    }

    /**
     * Sets the value of the internalTransactionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalTransactionDescription(String value) {
        this.internalTransactionDescription = value;
    }

    /**
     * Gets the value of the internalTransactionDescriptionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInternalTransactionDescriptionNumber() {
        return internalTransactionDescriptionNumber;
    }

    /**
     * Sets the value of the internalTransactionDescriptionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInternalTransactionDescriptionNumber(Long value) {
        this.internalTransactionDescriptionNumber = value;
    }

}
