//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ArrayOfRtxn_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ArrayOfRtxn");
    private final static QName _Rtxn_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "Rtxn");
    private final static QName _ArrayOfExchTxn_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ArrayOfExchTxn");
    private final static QName _ExchTxn_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ExchTxn");
    private final static QName _ArrayOfSpreadDetail_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ArrayOfSpreadDetail");
    private final static QName _SpreadDetail_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "SpreadDetail");
    private final static QName _ArrayOfTransaction_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ArrayOfTransaction");
    private final static QName _Transaction_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "Transaction");
    private final static QName _ArrayOfTransactionBalanceType_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ArrayOfTransactionBalanceType");
    private final static QName _TransactionBalanceType_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "TransactionBalanceType");
    private final static QName _ExtRtxnDescription_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ExtRtxnDescription");
    private final static QName _ArrayOfFundAmountDetail_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "ArrayOfFundAmountDetail");
    private final static QName _FundAmountDetail_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "FundAmountDetail");
    private final static QName _IntRtxnDescription_QNAME = new QName("http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", "IntRtxnDescription");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ArrayOfRtxn }
     * 
     */
    public ArrayOfRtxn createArrayOfRtxn() {
        return new ArrayOfRtxn();
    }

    /**
     * Create an instance of {@link Rtxn }
     * 
     */
    public Rtxn createRtxn() {
        return new Rtxn();
    }

    /**
     * Create an instance of {@link ArrayOfExchTxn }
     * 
     */
    public ArrayOfExchTxn createArrayOfExchTxn() {
        return new ArrayOfExchTxn();
    }

    /**
     * Create an instance of {@link ExchTxn }
     * 
     */
    public ExchTxn createExchTxn() {
        return new ExchTxn();
    }

    /**
     * Create an instance of {@link ArrayOfSpreadDetail }
     * 
     */
    public ArrayOfSpreadDetail createArrayOfSpreadDetail() {
        return new ArrayOfSpreadDetail();
    }

    /**
     * Create an instance of {@link SpreadDetail }
     * 
     */
    public SpreadDetail createSpreadDetail() {
        return new SpreadDetail();
    }

    /**
     * Create an instance of {@link ArrayOfTransaction }
     * 
     */
    public ArrayOfTransaction createArrayOfTransaction() {
        return new ArrayOfTransaction();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link ArrayOfTransactionBalanceType }
     * 
     */
    public ArrayOfTransactionBalanceType createArrayOfTransactionBalanceType() {
        return new ArrayOfTransactionBalanceType();
    }

    /**
     * Create an instance of {@link TransactionBalanceType }
     * 
     */
    public TransactionBalanceType createTransactionBalanceType() {
        return new TransactionBalanceType();
    }

    /**
     * Create an instance of {@link ExtRtxnDescription }
     * 
     */
    public ExtRtxnDescription createExtRtxnDescription() {
        return new ExtRtxnDescription();
    }

    /**
     * Create an instance of {@link ArrayOfFundAmountDetail }
     * 
     */
    public ArrayOfFundAmountDetail createArrayOfFundAmountDetail() {
        return new ArrayOfFundAmountDetail();
    }

    /**
     * Create an instance of {@link FundAmountDetail }
     * 
     */
    public FundAmountDetail createFundAmountDetail() {
        return new FundAmountDetail();
    }

    /**
     * Create an instance of {@link IntRtxnDescription }
     * 
     */
    public IntRtxnDescription createIntRtxnDescription() {
        return new IntRtxnDescription();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfRtxn }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfRtxn }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ArrayOfRtxn")
    public JAXBElement<ArrayOfRtxn> createArrayOfRtxn(ArrayOfRtxn value) {
        return new JAXBElement<ArrayOfRtxn>(_ArrayOfRtxn_QNAME, ArrayOfRtxn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rtxn }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Rtxn }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "Rtxn")
    public JAXBElement<Rtxn> createRtxn(Rtxn value) {
        return new JAXBElement<Rtxn>(_Rtxn_QNAME, Rtxn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfExchTxn }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfExchTxn }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ArrayOfExchTxn")
    public JAXBElement<ArrayOfExchTxn> createArrayOfExchTxn(ArrayOfExchTxn value) {
        return new JAXBElement<ArrayOfExchTxn>(_ArrayOfExchTxn_QNAME, ArrayOfExchTxn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExchTxn }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExchTxn }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ExchTxn")
    public JAXBElement<ExchTxn> createExchTxn(ExchTxn value) {
        return new JAXBElement<ExchTxn>(_ExchTxn_QNAME, ExchTxn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfSpreadDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfSpreadDetail }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ArrayOfSpreadDetail")
    public JAXBElement<ArrayOfSpreadDetail> createArrayOfSpreadDetail(ArrayOfSpreadDetail value) {
        return new JAXBElement<ArrayOfSpreadDetail>(_ArrayOfSpreadDetail_QNAME, ArrayOfSpreadDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpreadDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SpreadDetail }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "SpreadDetail")
    public JAXBElement<SpreadDetail> createSpreadDetail(SpreadDetail value) {
        return new JAXBElement<SpreadDetail>(_SpreadDetail_QNAME, SpreadDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTransaction }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfTransaction }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ArrayOfTransaction")
    public JAXBElement<ArrayOfTransaction> createArrayOfTransaction(ArrayOfTransaction value) {
        return new JAXBElement<ArrayOfTransaction>(_ArrayOfTransaction_QNAME, ArrayOfTransaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transaction }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Transaction }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "Transaction")
    public JAXBElement<Transaction> createTransaction(Transaction value) {
        return new JAXBElement<Transaction>(_Transaction_QNAME, Transaction.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfTransactionBalanceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfTransactionBalanceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ArrayOfTransactionBalanceType")
    public JAXBElement<ArrayOfTransactionBalanceType> createArrayOfTransactionBalanceType(ArrayOfTransactionBalanceType value) {
        return new JAXBElement<ArrayOfTransactionBalanceType>(_ArrayOfTransactionBalanceType_QNAME, ArrayOfTransactionBalanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionBalanceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionBalanceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "TransactionBalanceType")
    public JAXBElement<TransactionBalanceType> createTransactionBalanceType(TransactionBalanceType value) {
        return new JAXBElement<TransactionBalanceType>(_TransactionBalanceType_QNAME, TransactionBalanceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtRtxnDescription }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtRtxnDescription }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ExtRtxnDescription")
    public JAXBElement<ExtRtxnDescription> createExtRtxnDescription(ExtRtxnDescription value) {
        return new JAXBElement<ExtRtxnDescription>(_ExtRtxnDescription_QNAME, ExtRtxnDescription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfFundAmountDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfFundAmountDetail }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "ArrayOfFundAmountDetail")
    public JAXBElement<ArrayOfFundAmountDetail> createArrayOfFundAmountDetail(ArrayOfFundAmountDetail value) {
        return new JAXBElement<ArrayOfFundAmountDetail>(_ArrayOfFundAmountDetail_QNAME, ArrayOfFundAmountDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FundAmountDetail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link FundAmountDetail }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "FundAmountDetail")
    public JAXBElement<FundAmountDetail> createFundAmountDetail(FundAmountDetail value) {
        return new JAXBElement<FundAmountDetail>(_FundAmountDetail_QNAME, FundAmountDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IntRtxnDescription }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IntRtxnDescription }{@code >}
     */
    @XmlElementDecl(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", name = "IntRtxnDescription")
    public JAXBElement<IntRtxnDescription> createIntRtxnDescription(IntRtxnDescription value) {
        return new JAXBElement<IntRtxnDescription>(_IntRtxnDescription_QNAME, IntRtxnDescription.class, null, value);
    }

}
