//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages;
