//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.31 at 03:26:52 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             A specific transaction record for the account.
 *             </summary>
 *             <remarks>This class is used by the <see cref="T:AccountTransactionHistoryResponse" /> class.</remarks>
 *             <tocexclude />
 * 
 * <p>Java class for Rtxn complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Rtxn"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AccountNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ActivityDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ApprovingPersonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ApprovingPersonNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="CheckNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="CurrentRtxnStatisticsCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CurrentRtxnStatisticsDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DebitCredit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EffectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ExchTxnGrp" type="{http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages}ArrayOfExchTxn" minOccurs="0"/&gt;
 *         &lt;element name="ExternalRtxnDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ExternalRtxnDescriptionNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="HoldAccountNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ImageID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InternalRtxnDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="InternalRtxnDescriptionNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="IsCustomerView" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsRecurring" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="IsReversal" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OriginatingPersonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="OriginatingPersonNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ParentAccountNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="ParentRtxnNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="PostDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="PriorAvailableBalance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="RtxnNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="RtxnReasonCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RtxnSourceCatCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RtxnSourceCd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RtxnTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RtxnTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RunningBalance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="SpreadDetails" type="{http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages}ArrayOfSpreadDetail" minOccurs="0"/&gt;
 *         &lt;element name="StandardIndustryClassCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StandardIndustrySubClassCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TimeUniqueExtension" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="TraceId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TraceNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="TransactionAuxNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="TransactionReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WaiveApprPersNbr" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rtxn", propOrder = {
    "accountNumber",
    "activityDateTime",
    "approvingPersonName",
    "approvingPersonNumber",
    "checkNumber",
    "currentRtxnStatisticsCode",
    "currentRtxnStatisticsDescription",
    "debitCredit",
    "effectiveDate",
    "exchTxnGrp",
    "externalRtxnDescription",
    "externalRtxnDescriptionNumber",
    "holdAccountNumber",
    "imageID",
    "internalRtxnDescription",
    "internalRtxnDescriptionNumber",
    "isCustomerView",
    "isRecurring",
    "isReversal",
    "originatingPersonName",
    "originatingPersonNumber",
    "parentAccountNumber",
    "parentRtxnNumber",
    "postDate",
    "priorAvailableBalance",
    "rtxnNumber",
    "rtxnReasonCd",
    "rtxnSourceCatCd",
    "rtxnSourceCd",
    "rtxnTypeCode",
    "rtxnTypeDescription",
    "runningBalance",
    "spreadDetails",
    "standardIndustryClassCode",
    "standardIndustrySubClassCode",
    "timeUniqueExtension",
    "traceId",
    "traceNumber",
    "transactionAmount",
    "transactionAuxNumber",
    "transactionReferenceNumber",
    "waiveApprPersNbr"
})
public class Rtxn {

    @XmlElement(name = "AccountNumber", nillable = true)
    protected Long accountNumber;
    @XmlElement(name = "ActivityDateTime", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activityDateTime;
    @XmlElement(name = "ApprovingPersonName", nillable = true)
    protected String approvingPersonName;
    @XmlElement(name = "ApprovingPersonNumber", nillable = true)
    protected Long approvingPersonNumber;
    @XmlElement(name = "CheckNumber", nillable = true)
    protected Long checkNumber;
    @XmlElement(name = "CurrentRtxnStatisticsCode", nillable = true)
    protected String currentRtxnStatisticsCode;
    @XmlElement(name = "CurrentRtxnStatisticsDescription", nillable = true)
    protected String currentRtxnStatisticsDescription;
    @XmlElement(name = "DebitCredit", nillable = true)
    protected String debitCredit;
    @XmlElement(name = "EffectiveDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "ExchTxnGrp", nillable = true)
    protected ArrayOfExchTxn exchTxnGrp;
    @XmlElement(name = "ExternalRtxnDescription", nillable = true)
    protected String externalRtxnDescription;
    @XmlElement(name = "ExternalRtxnDescriptionNumber", nillable = true)
    protected Long externalRtxnDescriptionNumber;
    @XmlElement(name = "HoldAccountNumber", nillable = true)
    protected Long holdAccountNumber;
    @XmlElement(name = "ImageID", nillable = true)
    protected String imageID;
    @XmlElement(name = "InternalRtxnDescription", nillable = true)
    protected String internalRtxnDescription;
    @XmlElement(name = "InternalRtxnDescriptionNumber", nillable = true)
    protected Long internalRtxnDescriptionNumber;
    @XmlElement(name = "IsCustomerView", nillable = true)
    protected Boolean isCustomerView;
    @XmlElement(name = "IsRecurring", nillable = true)
    protected Boolean isRecurring;
    @XmlElement(name = "IsReversal", nillable = true)
    protected Boolean isReversal;
    @XmlElement(name = "OriginatingPersonName", nillable = true)
    protected String originatingPersonName;
    @XmlElement(name = "OriginatingPersonNumber", nillable = true)
    protected Long originatingPersonNumber;
    @XmlElement(name = "ParentAccountNumber", nillable = true)
    protected Long parentAccountNumber;
    @XmlElement(name = "ParentRtxnNumber", nillable = true)
    protected Long parentRtxnNumber;
    @XmlElement(name = "PostDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar postDate;
    @XmlElement(name = "PriorAvailableBalance", nillable = true)
    protected Double priorAvailableBalance;
    @XmlElement(name = "RtxnNumber", nillable = true)
    protected Long rtxnNumber;
    @XmlElement(name = "RtxnReasonCd", nillable = true)
    protected String rtxnReasonCd;
    @XmlElement(name = "RtxnSourceCatCd", nillable = true)
    protected String rtxnSourceCatCd;
    @XmlElement(name = "RtxnSourceCd", nillable = true)
    protected String rtxnSourceCd;
    @XmlElement(name = "RtxnTypeCode", nillable = true)
    protected String rtxnTypeCode;
    @XmlElement(name = "RtxnTypeDescription", nillable = true)
    protected String rtxnTypeDescription;
    @XmlElement(name = "RunningBalance", nillable = true)
    protected Double runningBalance;
    @XmlElement(name = "SpreadDetails", nillable = true)
    protected ArrayOfSpreadDetail spreadDetails;
    @XmlElement(name = "StandardIndustryClassCode", nillable = true)
    protected String standardIndustryClassCode;
    @XmlElement(name = "StandardIndustrySubClassCode", nillable = true)
    protected String standardIndustrySubClassCode;
    @XmlElement(name = "TimeUniqueExtension", nillable = true)
    protected Long timeUniqueExtension;
    @XmlElement(name = "TraceId", nillable = true)
    protected String traceId;
    @XmlElement(name = "TraceNumber", nillable = true)
    protected Long traceNumber;
    @XmlElement(name = "TransactionAmount", nillable = true)
    protected Double transactionAmount;
    @XmlElement(name = "TransactionAuxNumber", nillable = true)
    protected Long transactionAuxNumber;
    @XmlElement(name = "TransactionReferenceNumber", nillable = true)
    protected String transactionReferenceNumber;
    @XmlElement(name = "WaiveApprPersNbr", nillable = true)
    protected Long waiveApprPersNbr;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAccountNumber(Long value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the activityDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActivityDateTime() {
        return activityDateTime;
    }

    /**
     * Sets the value of the activityDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivityDateTime(XMLGregorianCalendar value) {
        this.activityDateTime = value;
    }

    /**
     * Gets the value of the approvingPersonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovingPersonName() {
        return approvingPersonName;
    }

    /**
     * Sets the value of the approvingPersonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovingPersonName(String value) {
        this.approvingPersonName = value;
    }

    /**
     * Gets the value of the approvingPersonNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getApprovingPersonNumber() {
        return approvingPersonNumber;
    }

    /**
     * Sets the value of the approvingPersonNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setApprovingPersonNumber(Long value) {
        this.approvingPersonNumber = value;
    }

    /**
     * Gets the value of the checkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCheckNumber() {
        return checkNumber;
    }

    /**
     * Sets the value of the checkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCheckNumber(Long value) {
        this.checkNumber = value;
    }

    /**
     * Gets the value of the currentRtxnStatisticsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentRtxnStatisticsCode() {
        return currentRtxnStatisticsCode;
    }

    /**
     * Sets the value of the currentRtxnStatisticsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentRtxnStatisticsCode(String value) {
        this.currentRtxnStatisticsCode = value;
    }

    /**
     * Gets the value of the currentRtxnStatisticsDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentRtxnStatisticsDescription() {
        return currentRtxnStatisticsDescription;
    }

    /**
     * Sets the value of the currentRtxnStatisticsDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentRtxnStatisticsDescription(String value) {
        this.currentRtxnStatisticsDescription = value;
    }

    /**
     * Gets the value of the debitCredit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitCredit() {
        return debitCredit;
    }

    /**
     * Sets the value of the debitCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitCredit(String value) {
        this.debitCredit = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the exchTxnGrp property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfExchTxn }
     *     
     */
    public ArrayOfExchTxn getExchTxnGrp() {
        return exchTxnGrp;
    }

    /**
     * Sets the value of the exchTxnGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfExchTxn }
     *     
     */
    public void setExchTxnGrp(ArrayOfExchTxn value) {
        this.exchTxnGrp = value;
    }

    /**
     * Gets the value of the externalRtxnDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalRtxnDescription() {
        return externalRtxnDescription;
    }

    /**
     * Sets the value of the externalRtxnDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalRtxnDescription(String value) {
        this.externalRtxnDescription = value;
    }

    /**
     * Gets the value of the externalRtxnDescriptionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getExternalRtxnDescriptionNumber() {
        return externalRtxnDescriptionNumber;
    }

    /**
     * Sets the value of the externalRtxnDescriptionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setExternalRtxnDescriptionNumber(Long value) {
        this.externalRtxnDescriptionNumber = value;
    }

    /**
     * Gets the value of the holdAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getHoldAccountNumber() {
        return holdAccountNumber;
    }

    /**
     * Sets the value of the holdAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHoldAccountNumber(Long value) {
        this.holdAccountNumber = value;
    }

    /**
     * Gets the value of the imageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageID() {
        return imageID;
    }

    /**
     * Sets the value of the imageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageID(String value) {
        this.imageID = value;
    }

    /**
     * Gets the value of the internalRtxnDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalRtxnDescription() {
        return internalRtxnDescription;
    }

    /**
     * Sets the value of the internalRtxnDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalRtxnDescription(String value) {
        this.internalRtxnDescription = value;
    }

    /**
     * Gets the value of the internalRtxnDescriptionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInternalRtxnDescriptionNumber() {
        return internalRtxnDescriptionNumber;
    }

    /**
     * Sets the value of the internalRtxnDescriptionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInternalRtxnDescriptionNumber(Long value) {
        this.internalRtxnDescriptionNumber = value;
    }

    /**
     * Gets the value of the isCustomerView property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCustomerView() {
        return isCustomerView;
    }

    /**
     * Sets the value of the isCustomerView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCustomerView(Boolean value) {
        this.isCustomerView = value;
    }

    /**
     * Gets the value of the isRecurring property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRecurring() {
        return isRecurring;
    }

    /**
     * Sets the value of the isRecurring property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRecurring(Boolean value) {
        this.isRecurring = value;
    }

    /**
     * Gets the value of the isReversal property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsReversal() {
        return isReversal;
    }

    /**
     * Sets the value of the isReversal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsReversal(Boolean value) {
        this.isReversal = value;
    }

    /**
     * Gets the value of the originatingPersonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginatingPersonName() {
        return originatingPersonName;
    }

    /**
     * Sets the value of the originatingPersonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginatingPersonName(String value) {
        this.originatingPersonName = value;
    }

    /**
     * Gets the value of the originatingPersonNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOriginatingPersonNumber() {
        return originatingPersonNumber;
    }

    /**
     * Sets the value of the originatingPersonNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOriginatingPersonNumber(Long value) {
        this.originatingPersonNumber = value;
    }

    /**
     * Gets the value of the parentAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getParentAccountNumber() {
        return parentAccountNumber;
    }

    /**
     * Sets the value of the parentAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setParentAccountNumber(Long value) {
        this.parentAccountNumber = value;
    }

    /**
     * Gets the value of the parentRtxnNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getParentRtxnNumber() {
        return parentRtxnNumber;
    }

    /**
     * Sets the value of the parentRtxnNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setParentRtxnNumber(Long value) {
        this.parentRtxnNumber = value;
    }

    /**
     * Gets the value of the postDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostDate() {
        return postDate;
    }

    /**
     * Sets the value of the postDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostDate(XMLGregorianCalendar value) {
        this.postDate = value;
    }

    /**
     * Gets the value of the priorAvailableBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriorAvailableBalance() {
        return priorAvailableBalance;
    }

    /**
     * Sets the value of the priorAvailableBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriorAvailableBalance(Double value) {
        this.priorAvailableBalance = value;
    }

    /**
     * Gets the value of the rtxnNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRtxnNumber() {
        return rtxnNumber;
    }

    /**
     * Sets the value of the rtxnNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRtxnNumber(Long value) {
        this.rtxnNumber = value;
    }

    /**
     * Gets the value of the rtxnReasonCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnReasonCd() {
        return rtxnReasonCd;
    }

    /**
     * Sets the value of the rtxnReasonCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnReasonCd(String value) {
        this.rtxnReasonCd = value;
    }

    /**
     * Gets the value of the rtxnSourceCatCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnSourceCatCd() {
        return rtxnSourceCatCd;
    }

    /**
     * Sets the value of the rtxnSourceCatCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnSourceCatCd(String value) {
        this.rtxnSourceCatCd = value;
    }

    /**
     * Gets the value of the rtxnSourceCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnSourceCd() {
        return rtxnSourceCd;
    }

    /**
     * Sets the value of the rtxnSourceCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnSourceCd(String value) {
        this.rtxnSourceCd = value;
    }

    /**
     * Gets the value of the rtxnTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnTypeCode() {
        return rtxnTypeCode;
    }

    /**
     * Sets the value of the rtxnTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnTypeCode(String value) {
        this.rtxnTypeCode = value;
    }

    /**
     * Gets the value of the rtxnTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtxnTypeDescription() {
        return rtxnTypeDescription;
    }

    /**
     * Sets the value of the rtxnTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtxnTypeDescription(String value) {
        this.rtxnTypeDescription = value;
    }

    /**
     * Gets the value of the runningBalance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRunningBalance() {
        return runningBalance;
    }

    /**
     * Sets the value of the runningBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRunningBalance(Double value) {
        this.runningBalance = value;
    }

    /**
     * Gets the value of the spreadDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSpreadDetail }
     *     
     */
    public ArrayOfSpreadDetail getSpreadDetails() {
        return spreadDetails;
    }

    /**
     * Sets the value of the spreadDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSpreadDetail }
     *     
     */
    public void setSpreadDetails(ArrayOfSpreadDetail value) {
        this.spreadDetails = value;
    }

    /**
     * Gets the value of the standardIndustryClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardIndustryClassCode() {
        return standardIndustryClassCode;
    }

    /**
     * Sets the value of the standardIndustryClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardIndustryClassCode(String value) {
        this.standardIndustryClassCode = value;
    }

    /**
     * Gets the value of the standardIndustrySubClassCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardIndustrySubClassCode() {
        return standardIndustrySubClassCode;
    }

    /**
     * Sets the value of the standardIndustrySubClassCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardIndustrySubClassCode(String value) {
        this.standardIndustrySubClassCode = value;
    }

    /**
     * Gets the value of the timeUniqueExtension property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeUniqueExtension() {
        return timeUniqueExtension;
    }

    /**
     * Sets the value of the timeUniqueExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeUniqueExtension(Long value) {
        this.timeUniqueExtension = value;
    }

    /**
     * Gets the value of the traceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * Sets the value of the traceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTraceId(String value) {
        this.traceId = value;
    }

    /**
     * Gets the value of the traceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTraceNumber() {
        return traceNumber;
    }

    /**
     * Sets the value of the traceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTraceNumber(Long value) {
        this.traceNumber = value;
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTransactionAmount(Double value) {
        this.transactionAmount = value;
    }

    /**
     * Gets the value of the transactionAuxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTransactionAuxNumber() {
        return transactionAuxNumber;
    }

    /**
     * Sets the value of the transactionAuxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransactionAuxNumber(Long value) {
        this.transactionAuxNumber = value;
    }

    /**
     * Gets the value of the transactionReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionReferenceNumber() {
        return transactionReferenceNumber;
    }

    /**
     * Sets the value of the transactionReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionReferenceNumber(String value) {
        this.transactionReferenceNumber = value;
    }

    /**
     * Gets the value of the waiveApprPersNbr property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWaiveApprPersNbr() {
        return waiveApprPersNbr;
    }

    /**
     * Sets the value of the waiveApprPersNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWaiveApprPersNbr(Long value) {
        this.waiveApprPersNbr = value;
    }

}
