//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.09.01 at 08:54:41 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.messages;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <summary>
 *             A specific transaction record for the account.
 *             </summary>
 *             <remarks>This class is used by the <see cref="T:TransactionHistoryInquiryResponse" /> class.</remarks>
 *             <tocexclude />
 * 
 * <p>Java class for Transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transaction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ActivityDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="BalanceTypes" type="{http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages}ArrayOfTransactionBalanceType" minOccurs="0"/&gt;
 *         &lt;element name="CheckNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="CurrentTransactionStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EffectiveDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="ExternalTransactionDescription" type="{http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages}ExtRtxnDescription" minOccurs="0"/&gt;
 *         &lt;element name="Funds" type="{http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages}ArrayOfFundAmountDetail" minOccurs="0"/&gt;
 *         &lt;element name="InternalTransactionDescription" type="{http://schemas.datacontract.org/2004/07/OpenSolutions.CoreApiService.Services.Messages}IntRtxnDescription" minOccurs="0"/&gt;
 *         &lt;element name="IsCustomerView" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="PostDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="TimeUniqueExtension" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="TransactionAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="TransactionNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="TransactionReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionSourceCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionSourceCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TransactionTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transaction", propOrder = {
    "activityDateTime",
    "balanceTypes",
    "checkNumber",
    "currentTransactionStatus",
    "effectiveDate",
    "externalTransactionDescription",
    "funds",
    "internalTransactionDescription",
    "isCustomerView",
    "postDate",
    "timeUniqueExtension",
    "transactionAmount",
    "transactionNumber",
    "transactionReferenceNumber",
    "transactionSourceCategoryCode",
    "transactionSourceCode",
    "transactionTypeCode",
    "transactionTypeDescription"
})
public class Transaction {

    @XmlElement(name = "ActivityDateTime", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar activityDateTime;
    @XmlElement(name = "BalanceTypes", nillable = true)
    protected ArrayOfTransactionBalanceType balanceTypes;
    @XmlElement(name = "CheckNumber", nillable = true)
    protected Long checkNumber;
    @XmlElement(name = "CurrentTransactionStatus", nillable = true)
    protected String currentTransactionStatus;
    @XmlElement(name = "EffectiveDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "ExternalTransactionDescription", nillable = true)
    protected ExtRtxnDescription externalTransactionDescription;
    @XmlElement(name = "Funds", nillable = true)
    protected ArrayOfFundAmountDetail funds;
    @XmlElement(name = "InternalTransactionDescription", nillable = true)
    protected IntRtxnDescription internalTransactionDescription;
    @XmlElement(name = "IsCustomerView", nillable = true)
    protected Boolean isCustomerView;
    @XmlElement(name = "PostDate", nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar postDate;
    @XmlElement(name = "TimeUniqueExtension", nillable = true)
    protected Long timeUniqueExtension;
    @XmlElement(name = "TransactionAmount", nillable = true)
    protected Double transactionAmount;
    @XmlElement(name = "TransactionNumber", nillable = true)
    protected Long transactionNumber;
    @XmlElement(name = "TransactionReferenceNumber", nillable = true)
    protected String transactionReferenceNumber;
    @XmlElement(name = "TransactionSourceCategoryCode", nillable = true)
    protected String transactionSourceCategoryCode;
    @XmlElement(name = "TransactionSourceCode", nillable = true)
    protected String transactionSourceCode;
    @XmlElement(name = "TransactionTypeCode", nillable = true)
    protected String transactionTypeCode;
    @XmlElement(name = "TransactionTypeDescription", nillable = true)
    protected String transactionTypeDescription;

    /**
     * Gets the value of the activityDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActivityDateTime() {
        return activityDateTime;
    }

    /**
     * Sets the value of the activityDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivityDateTime(XMLGregorianCalendar value) {
        this.activityDateTime = value;
    }

    /**
     * Gets the value of the balanceTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfTransactionBalanceType }
     *     
     */
    public ArrayOfTransactionBalanceType getBalanceTypes() {
        return balanceTypes;
    }

    /**
     * Sets the value of the balanceTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfTransactionBalanceType }
     *     
     */
    public void setBalanceTypes(ArrayOfTransactionBalanceType value) {
        this.balanceTypes = value;
    }

    /**
     * Gets the value of the checkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCheckNumber() {
        return checkNumber;
    }

    /**
     * Sets the value of the checkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCheckNumber(Long value) {
        this.checkNumber = value;
    }

    /**
     * Gets the value of the currentTransactionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentTransactionStatus() {
        return currentTransactionStatus;
    }

    /**
     * Sets the value of the currentTransactionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentTransactionStatus(String value) {
        this.currentTransactionStatus = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the externalTransactionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ExtRtxnDescription }
     *     
     */
    public ExtRtxnDescription getExternalTransactionDescription() {
        return externalTransactionDescription;
    }

    /**
     * Sets the value of the externalTransactionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtRtxnDescription }
     *     
     */
    public void setExternalTransactionDescription(ExtRtxnDescription value) {
        this.externalTransactionDescription = value;
    }

    /**
     * Gets the value of the funds property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfFundAmountDetail }
     *     
     */
    public ArrayOfFundAmountDetail getFunds() {
        return funds;
    }

    /**
     * Sets the value of the funds property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfFundAmountDetail }
     *     
     */
    public void setFunds(ArrayOfFundAmountDetail value) {
        this.funds = value;
    }

    /**
     * Gets the value of the internalTransactionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link IntRtxnDescription }
     *     
     */
    public IntRtxnDescription getInternalTransactionDescription() {
        return internalTransactionDescription;
    }

    /**
     * Sets the value of the internalTransactionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntRtxnDescription }
     *     
     */
    public void setInternalTransactionDescription(IntRtxnDescription value) {
        this.internalTransactionDescription = value;
    }

    /**
     * Gets the value of the isCustomerView property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCustomerView() {
        return isCustomerView;
    }

    /**
     * Sets the value of the isCustomerView property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCustomerView(Boolean value) {
        this.isCustomerView = value;
    }

    /**
     * Gets the value of the postDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPostDate() {
        return postDate;
    }

    /**
     * Sets the value of the postDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPostDate(XMLGregorianCalendar value) {
        this.postDate = value;
    }

    /**
     * Gets the value of the timeUniqueExtension property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeUniqueExtension() {
        return timeUniqueExtension;
    }

    /**
     * Sets the value of the timeUniqueExtension property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeUniqueExtension(Long value) {
        this.timeUniqueExtension = value;
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTransactionAmount(Double value) {
        this.transactionAmount = value;
    }

    /**
     * Gets the value of the transactionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTransactionNumber() {
        return transactionNumber;
    }

    /**
     * Sets the value of the transactionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTransactionNumber(Long value) {
        this.transactionNumber = value;
    }

    /**
     * Gets the value of the transactionReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionReferenceNumber() {
        return transactionReferenceNumber;
    }

    /**
     * Sets the value of the transactionReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionReferenceNumber(String value) {
        this.transactionReferenceNumber = value;
    }

    /**
     * Gets the value of the transactionSourceCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSourceCategoryCode() {
        return transactionSourceCategoryCode;
    }

    /**
     * Sets the value of the transactionSourceCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSourceCategoryCode(String value) {
        this.transactionSourceCategoryCode = value;
    }

    /**
     * Gets the value of the transactionSourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionSourceCode() {
        return transactionSourceCode;
    }

    /**
     * Sets the value of the transactionSourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionSourceCode(String value) {
        this.transactionSourceCode = value;
    }

    /**
     * Gets the value of the transactionTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionTypeCode() {
        return transactionTypeCode;
    }

    /**
     * Sets the value of the transactionTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionTypeCode(String value) {
        this.transactionTypeCode = value;
    }

    /**
     * Gets the value of the transactionTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionTypeDescription() {
        return transactionTypeDescription;
    }

    /**
     * Sets the value of the transactionTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionTypeDescription(String value) {
        this.transactionTypeDescription = value;
    }

}
