//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://schemas.microsoft.com/2003/10/Serialization/Arrays", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.arrays;
