//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.31 at 03:26:52 PM PDT 
//


package com.dep.integration.transaction.hook.fiserv.dto.jaxb.envelope;

import com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi.SubmitRequest;
import com.dep.integration.transaction.hook.fiserv.dto.jaxb.coreapi.SubmitRequestResponse;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element ref="{http://www.opensolutions.com/CoreApi}SubmitRequest"/&gt;
 *         &lt;element ref="{http://www.opensolutions.com/CoreApi}SubmitRequestResponse"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "submitRequest",
    "submitRequestResponse"
})
public class Body {

    @XmlElement(name = "SubmitRequest", namespace = "http://www.opensolutions.com/CoreApi")
    protected SubmitRequest submitRequest;
    @XmlElement(name = "SubmitRequestResponse", namespace = "http://www.opensolutions.com/CoreApi")
    protected SubmitRequestResponse submitRequestResponse;

    /**
     * Gets the value of the submitRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitRequest }
     *     
     */
    public SubmitRequest getSubmitRequest() {
        return submitRequest;
    }

    /**
     * Sets the value of the submitRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitRequest }
     *     
     */
    public void setSubmitRequest(SubmitRequest value) {
        this.submitRequest = value;
    }

    /**
     * Gets the value of the submitRequestResponse property.
     * 
     * @return
     *     possible object is
     *     {@link SubmitRequestResponse }
     *     
     */
    public SubmitRequestResponse getSubmitRequestResponse() {
        return submitRequestResponse;
    }

    /**
     * Sets the value of the submitRequestResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubmitRequestResponse }
     *     
     */
    public void setSubmitRequestResponse(SubmitRequestResponse value) {
        this.submitRequestResponse = value;
    }

}
