//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.coreapi;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import com.dep.integration.billpayment.hook.fiserv.dto.jaxb.billpaymaintenance.ArrayOfBillPayAllotments;


/**
 * &lt;p&gt;Java class for BillPayMaintenanceRequest complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="BillPayMaintenanceRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opensolutions.com/CoreApi}ExtensionRequestBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BillPaymentAllotments" type="{http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance}ArrayOfBillPayAllotments" minOccurs="0"/&gt;
 *         &lt;element name="EAgreementNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="OrganizationNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="PersonNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element name="UserId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPayMaintenanceRequest", propOrder = {
    "billPaymentAllotments",
    "eAgreementNumber",
    "organizationNumber",
    "personNumber",
    "userId"
})
public class BillPayMaintenanceRequest
    extends ExtensionRequestBase
{

    @XmlElement(name = "BillPaymentAllotments", nillable = true)
    protected ArrayOfBillPayAllotments billPaymentAllotments;
    @XmlElement(name = "EAgreementNumber", nillable = true)
    protected Long eAgreementNumber;
    @XmlElement(name = "OrganizationNumber", nillable = true)
    protected Long organizationNumber;
    @XmlElement(name = "PersonNumber", nillable = true)
    protected Long personNumber;
    @XmlElement(name = "UserId", nillable = true)
    protected String userId;

    /**
     * Gets the value of the billPaymentAllotments property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBillPayAllotments }
     *     
     */
    public ArrayOfBillPayAllotments getBillPaymentAllotments() {
        return billPaymentAllotments;
    }

    /**
     * Sets the value of the billPaymentAllotments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBillPayAllotments }
     *     
     */
    public void setBillPaymentAllotments(ArrayOfBillPayAllotments value) {
        this.billPaymentAllotments = value;
    }

    /**
     * Gets the value of the eAgreementNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getEAgreementNumber() {
        return eAgreementNumber;
    }

    /**
     * Sets the value of the eAgreementNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setEAgreementNumber(Long value) {
        this.eAgreementNumber = value;
    }

    /**
     * Gets the value of the organizationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOrganizationNumber() {
        return organizationNumber;
    }

    /**
     * Sets the value of the organizationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOrganizationNumber(Long value) {
        this.organizationNumber = value;
    }

    /**
     * Gets the value of the personNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPersonNumber() {
        return personNumber;
    }

    /**
     * Sets the value of the personNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPersonNumber(Long value) {
        this.personNumber = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

}
