//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.coreapi;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import com.dep.integration.billpayment.hook.fiserv.dto.jaxb.billpaymaintenance.ArrayOfBillPaymentResponseAllotments;


/**
 * &lt;p&gt;Java class for BillPayMaintenanceResponse complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="BillPayMaintenanceResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opensolutions.com/CoreApi}ExtensionResponseBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BillPaymentResponseAllotments" type="{http://schemas.datacontract.org/2004/07/CoreApiExtension.Messages.BillPayMaintenance}ArrayOfBillPaymentResponseAllotments" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillPayMaintenanceResponse", propOrder = {
    "billPaymentResponseAllotments"
})
public class BillPayMaintenanceResponse
    extends ExtensionResponseBase
{

    @XmlElement(name = "BillPaymentResponseAllotments", nillable = true)
    protected ArrayOfBillPaymentResponseAllotments billPaymentResponseAllotments;

    /**
     * Gets the value of the billPaymentResponseAllotments property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBillPaymentResponseAllotments }
     *     
     */
    public ArrayOfBillPaymentResponseAllotments getBillPaymentResponseAllotments() {
        return billPaymentResponseAllotments;
    }

    /**
     * Sets the value of the billPaymentResponseAllotments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBillPaymentResponseAllotments }
     *     
     */
    public void setBillPaymentResponseAllotments(ArrayOfBillPaymentResponseAllotments value) {
        this.billPaymentResponseAllotments = value;
    }

}
