//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.coreapi;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.opensolutions.coreapi package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ExtensionRequestBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ExtensionRequestBase");
    private static final QName _BillPayMaintenanceRequest_QNAME = new QName("http://www.opensolutions.com/CoreApi", "BillPayMaintenanceRequest");
    private static final QName _ExtensionResponseBase_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ExtensionResponseBase");
    private static final QName _ArrayOfExtensionError_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ArrayOfExtensionError");
    private static final QName _ExtensionError_QNAME = new QName("http://www.opensolutions.com/CoreApi", "ExtensionError");
    private static final QName _BillPayMaintenanceResponse_QNAME = new QName("http://www.opensolutions.com/CoreApi", "BillPayMaintenanceResponse");
    private static final QName _TransactionInput_QNAME = new QName("http://www.opensolutions.com/CoreApi", "TransactionInput");
    private static final QName _Input_QNAME = new QName("http://www.opensolutions.com/CoreApi", "Input");
    private static final QName _UAInput_QNAME = new QName("http://www.opensolutions.com/CoreApi", "UAInput");
    private static final QName _TransactionOutput_QNAME = new QName("http://www.opensolutions.com/CoreApi", "TransactionOutput");
    private static final QName _Output_QNAME = new QName("http://www.opensolutions.com/CoreApi", "Output");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.opensolutions.coreapi
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtensionRequestBase }
     * 
     * @return
     *     the new instance of {@link ExtensionRequestBase }
     */
    public ExtensionRequestBase createExtensionRequestBase() {
        return new ExtensionRequestBase();
    }

    /**
     * Create an instance of {@link BillPayMaintenanceRequest }
     * 
     * @return
     *     the new instance of {@link BillPayMaintenanceRequest }
     */
    public BillPayMaintenanceRequest createBillPayMaintenanceRequest() {
        return new BillPayMaintenanceRequest();
    }

    /**
     * Create an instance of {@link ExtensionResponseBase }
     * 
     * @return
     *     the new instance of {@link ExtensionResponseBase }
     */
    public ExtensionResponseBase createExtensionResponseBase() {
        return new ExtensionResponseBase();
    }

    /**
     * Create an instance of {@link ArrayOfExtensionError }
     * 
     * @return
     *     the new instance of {@link ArrayOfExtensionError }
     */
    public ArrayOfExtensionError createArrayOfExtensionError() {
        return new ArrayOfExtensionError();
    }

    /**
     * Create an instance of {@link ExtensionError }
     * 
     * @return
     *     the new instance of {@link ExtensionError }
     */
    public ExtensionError createExtensionError() {
        return new ExtensionError();
    }

    /**
     * Create an instance of {@link BillPayMaintenanceResponse }
     * 
     * @return
     *     the new instance of {@link BillPayMaintenanceResponse }
     */
    public BillPayMaintenanceResponse createBillPayMaintenanceResponse() {
        return new BillPayMaintenanceResponse();
    }

    /**
     * Create an instance of {@link SubmitRequest }
     * 
     * @return
     *     the new instance of {@link SubmitRequest }
     */
    public SubmitRequest createSubmitRequest() {
        return new SubmitRequest();
    }

    /**
     * Create an instance of {@link TransactionInput }
     * 
     * @return
     *     the new instance of {@link TransactionInput }
     */
    public TransactionInput createTransactionInput() {
        return new TransactionInput();
    }

    /**
     * Create an instance of {@link Input }
     * 
     * @return
     *     the new instance of {@link Input }
     */
    public Input createInput() {
        return new Input();
    }

    /**
     * Create an instance of {@link UAInput }
     * 
     * @return
     *     the new instance of {@link UAInput }
     */
    public UAInput createUAInput() {
        return new UAInput();
    }

    /**
     * Create an instance of {@link SubmitRequestResponse }
     * 
     * @return
     *     the new instance of {@link SubmitRequestResponse }
     */
    public SubmitRequestResponse createSubmitRequestResponse() {
        return new SubmitRequestResponse();
    }

    /**
     * Create an instance of {@link TransactionOutput }
     * 
     * @return
     *     the new instance of {@link TransactionOutput }
     */
    public TransactionOutput createTransactionOutput() {
        return new TransactionOutput();
    }

    /**
     * Create an instance of {@link Output }
     * 
     * @return
     *     the new instance of {@link Output }
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionRequestBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtensionRequestBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ExtensionRequestBase")
    public JAXBElement<ExtensionRequestBase> createExtensionRequestBase(ExtensionRequestBase value) {
        return new JAXBElement<>(_ExtensionRequestBase_QNAME, ExtensionRequestBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillPayMaintenanceRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BillPayMaintenanceRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "BillPayMaintenanceRequest")
    public JAXBElement<BillPayMaintenanceRequest> createBillPayMaintenanceRequest(BillPayMaintenanceRequest value) {
        return new JAXBElement<>(_BillPayMaintenanceRequest_QNAME, BillPayMaintenanceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionResponseBase }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtensionResponseBase }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ExtensionResponseBase")
    public JAXBElement<ExtensionResponseBase> createExtensionResponseBase(ExtensionResponseBase value) {
        return new JAXBElement<>(_ExtensionResponseBase_QNAME, ExtensionResponseBase.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfExtensionError }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfExtensionError }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ArrayOfExtensionError")
    public JAXBElement<ArrayOfExtensionError> createArrayOfExtensionError(ArrayOfExtensionError value) {
        return new JAXBElement<>(_ArrayOfExtensionError_QNAME, ArrayOfExtensionError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionError }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ExtensionError }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "ExtensionError")
    public JAXBElement<ExtensionError> createExtensionError(ExtensionError value) {
        return new JAXBElement<>(_ExtensionError_QNAME, ExtensionError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BillPayMaintenanceResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BillPayMaintenanceResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "BillPayMaintenanceResponse")
    public JAXBElement<BillPayMaintenanceResponse> createBillPayMaintenanceResponse(BillPayMaintenanceResponse value) {
        return new JAXBElement<>(_BillPayMaintenanceResponse_QNAME, BillPayMaintenanceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionInput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionInput }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "TransactionInput")
    public JAXBElement<TransactionInput> createTransactionInput(TransactionInput value) {
        return new JAXBElement<>(_TransactionInput_QNAME, TransactionInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Input }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Input }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "Input")
    public JAXBElement<Input> createInput(Input value) {
        return new JAXBElement<>(_Input_QNAME, Input.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UAInput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UAInput }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "UAInput")
    public JAXBElement<UAInput> createUAInput(UAInput value) {
        return new JAXBElement<>(_UAInput_QNAME, UAInput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionOutput }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionOutput }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "TransactionOutput")
    public JAXBElement<TransactionOutput> createTransactionOutput(TransactionOutput value) {
        return new JAXBElement<>(_TransactionOutput_QNAME, TransactionOutput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Output }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Output }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.opensolutions.com/CoreApi", name = "Output")
    public JAXBElement<Output> createOutput(Output value) {
        return new JAXBElement<>(_Output_QNAME, Output.class, null, value);
    }

}
