//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.coreapi;

import com.dep.integration.billpayment.hook.fiserv.dto.jaxb.arrays.ArrayOfanyType;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for Output complex type&lt;/p&gt;.
 *
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 *
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="Output"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExtensionResponses" type="{http://schemas.microsoft.com/2003/10/Serialization/Arrays}ArrayOfanyType" minOccurs="0"/&gt;
 *         &lt;element name="UserAuthentication" type="{http://www.opensolutions.com/CoreApi}UAOutput" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Output", propOrder = {
        "extensionResponses",
        "userAuthentication"
})
public class Output {

    @XmlElement(name = "ExtensionResponses", nillable = true)
    protected ArrayOfanyType extensionResponses;
    /**
     * &lt;summary&gt;
     *                         Wrapper tag that identifies if the request was successful and if not, a collection of one or more Errors.
     *                         &lt;/summary&gt;
     *
     */
    @XmlElement(name = "UserAuthentication", nillable = true)
    protected UAOutput userAuthentication;

    /**
     * Gets the value of the extensionResponses property.
     *
     * @return
     *     possible object is
     *     {@link ArrayOfanyType }
     *
     */
    public ArrayOfanyType getExtensionResponses() {
        return extensionResponses;
    }

    /**
     * Sets the value of the extensionResponses property.
     *
     * @param value
     *     allowed object is
     *     {@link ArrayOfanyType }
     *
     */
    public void setExtensionResponses(ArrayOfanyType value) {
        this.extensionResponses = value;
    }

    /**
     * &lt;summary&gt;
     *                         Wrapper tag that identifies if the request was successful and if not, a collection of one or more Errors.
     *                         &lt;/summary&gt;
     *
     * @return
     *     possible object is
     *     {@link UAOutput }
     *
     */
    public UAOutput getUserAuthentication() {
        return userAuthentication;
    }

    /**
     * Sets the value of the userAuthentication property.
     *
     * @param value
     *     allowed object is
     *     {@link UAOutput }
     *
     * @see #getUserAuthentication()
     */
    public void setUserAuthentication(UAOutput value) {
        this.userAuthentication = value;
    }

}

