//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.dep.integration.billpayment.hook.fiserv.dto.jaxb.coreapi;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * &lt;summary&gt;
 *                 Wrapper tag that identifies if the request was successful and if not, a collection of one or more Errors.
 *                 &lt;/summary&gt;
 * 
 * &lt;p&gt;Java class for UAOutput complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="UAOutput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Errors" type="{http://www.opensolutions.com/CoreApi}ArrayOfError" minOccurs="0"/&gt;
 *         &lt;element name="PersNbr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="WasSuccessful" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UAOutput", propOrder = {
    "errors",
    "persNbr",
    "wasSuccessful"
})
public class UAOutput {

    /**
     * &lt;summary&gt;
     *                         A collection of one or more authentication errors.
     *                         &lt;/summary&gt;
     * 
     */
    @XmlElement(name = "Errors", nillable = true)
    protected ArrayOfError errors;
    /**
     * &lt;summary&gt;
     *                         Logged-in user's persnbr
     *                         &lt;/summary&gt;
     * 
     */
    @XmlElement(name = "PersNbr", nillable = true)
    protected String persNbr;
    /**
     * &lt;summary&gt;
     *                         Indicates if the request was successful.
     *                         &lt;/summary&gt;
     * 
     */
    @XmlElement(name = "WasSuccessful", nillable = true)
    protected Boolean wasSuccessful;

    /**
     * &lt;summary&gt;
     *                         A collection of one or more authentication errors.
     *                         &lt;/summary&gt;
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfError }
     *     
     */
    public ArrayOfError getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfError }
     *     
     * @see #getErrors()
     */
    public void setErrors(ArrayOfError value) {
        this.errors = value;
    }

    /**
     * &lt;summary&gt;
     *                         Logged-in user's persnbr
     *                         &lt;/summary&gt;
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersNbr() {
        return persNbr;
    }

    /**
     * Sets the value of the persNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     * @see #getPersNbr()
     */
    public void setPersNbr(String value) {
        this.persNbr = value;
    }

    /**
     * &lt;summary&gt;
     *                         Indicates if the request was successful.
     *                         &lt;/summary&gt;
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWasSuccessful() {
        return wasSuccessful;
    }

    /**
     * Sets the value of the wasSuccessful property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     * @see #isWasSuccessful()
     */
    public void setWasSuccessful(Boolean value) {
        this.wasSuccessful = value;
    }

}
